### ISSUE TITLE
Wishlist Product Move to Cart API is not working.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#10]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**

**Description**
In wishlist API, there we have Move to Cart API, there it is working similarly as add and remove product to wishlist.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customers -> Wishlists -> Move to Cart.
**2.** API is not working.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/204729785-fcbe3f34-b115-4477-ae77-931745c7ff77.mp4

**Expected Result**

The functionality of the API should be sending wishlist product to the cart.

**Comment by Aqib-Webkul** [comment]
In this request URL is not hitting on the correct method, It should call method moveToCart() but it is calling method addOrRemove()

**Comment by amit-webkul** [comment]
The issue has been fixed.
![Screenshot from 2023-05-17 16-13-44](https://github.com/bagisto/rest-api/assets/121479029/e302a58f-214f-45dc-b423-0daff82ee6a3)

**Comment by Amitk-webkul** [comment]
This is working fine.[Here](https://tinyurl.com/2eyxyvbo)
