### ISSUE TITLE
When we update product using post method then shows an error, also status shows 500 internal server error, after solved these error but not update some fields

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#104]
When we update product using post method then shows an error, also status shows 500 internal server error, after solved these error but not update some fields

**How to Reproduce:**

**Issue 1:**

Step 1: Open postman add details related to product creates:

```
Method: Post
URL: http://localhost/bg-rest-api-2.0/public/api/v1/admin/catalog/products/16?_method=PUT
Form-data add prod. details. sku details should be unique
```

Showing an error like this:

![image](https://github.com/bagisto/rest-api/assets/63539748/ba6ead6c-13ab-4f1b-95fd-91fb0edeaf13)

After add channel showing locale error, after add locale then shows like this error:

![image](https://github.com/bagisto/rest-api/assets/63539748/6491ee6b-2441-4e51-bd24-d8e2e4a8280e)

Step 2: Now hit then updated product.

Step 3: **Now check the updated product here these field are not updated:**

- short_description
- description
- name
- meta title
- meta desc.
- meta keywords
- up-sell prod
- cross-sell prod

**Check the below fields that change value successfully:**

- sku
- url_key
- price
- weights 

**Issue 2:**

Should be product visible on front-end when we status updated from api side

**Note: Please check the below video for more references:**

https://webkul.chatwhizz.com/share/view-recording/65641eb1ef4e9e10eda56868 

**Possible Solution:**

- Should be change all fields when we updating from postman api side
- Should be product visible on front-end when we status updated from api side field is **status** 1 or 0

**Comment by Komal-sharma-2712** [comment]
I have checked this issue also, at this moment issue not resolved properly. 

**Need to fixed these points also:**

1. Should be change all fields when we updating from postman api side
2. Should be product visible on front-end when we status updated from api side field is status 1 or 0
3. Updated product here these field are not updated:

short_description
description
name
meta title
meta desc.
meta keywords
up-sell prod
cross-sell prod

**Note: Check all parameters from admin created api doc. Also, need to check all parameters from admin UI should be work all parameters**

**Comment by Komal-sharma-2712** [comment]
I have checked this issue again after new commits but issue not solved properly.

Need to fixed these points also:

1. Should be change all fields when we updating from postman api side
2. Should be product visible on front-end when we status updated from api side field is status 1 or 0

**Updated product here these field are not updated:**

- short_description
- description
- name
- meta title
- meta desc.
- meta keywords
- up-sell prod
- cross-sell prod
- cost field

```
"channels": null,
"short_description": null,
"description": null,
"name": null, 
"manage_stock": 0,
"meta_title": null,
"meta_keywords": null,
"meta_description": null,
```

![Screenshot from 2024-01-05 12-37-42](https://github.com/bagisto/rest-api/assets/63539748/e8dbe1d0-fbca-444c-8a86-0e4db3170441)


**Note: Fields not updating on admin panel and also cost filed not updated**

Need to fixed these issues also.

**Comment by Komal-sharma-2712** [comment]
I have checked again after new commit, but here product time shows an error. Please check the below video:

Shows an error on front end when we view the product, after update product from api side:

`"Diglactic\Breadcrumbs\Generator::push(): Argument #1 ($title) must be of type string, null given, called in /home/users/komal.sharma/www/html/rest2-api-2.0/routes/breadcrumbs.php on line 97 (View: /home/users/komal.sharma/www/html/rest2-api-2.0/packages/Webkul/Shop/src/Resources/views/components/breadcrumbs/index.blade.php) (View: /home/users/komal.sharma/www/html/rest2-api-2.0/packages/Webkul/Shop/src/Resources/views/components/breadcrumbs/index.blade.php)"`

https://webkul.chatwhizz.com/share/view-recording/659e6f36f0ffe846aae73946 

**Also, these fields not updated:**

- short_description
- description
- name
- cost field
- special-price-from
- special-price-to
- meta title
- meta desc.
- meta keywords
- up-sell prod
- cross-sell prod

Need to fix these issues also.

**Comment by himani-webkul** [comment]
Already fixed.
![Screenshot from 2024-01-11 12-21-41](https://github.com/bagisto/rest-api/assets/154529004/f15edc42-4eee-441b-8084-a48b7b978240)
![Screenshot from 2024-01-11 12-21-39](https://github.com/bagisto/rest-api/assets/154529004/711310f5-49d8-4cf9-9c28-58ff69cf9bdc)
![Screenshot from 2024-01-11 12-21-30](https://github.com/bagisto/rest-api/assets/154529004/0dab45a2-704a-465d-a830-c6a7e631636f)

**Comment by Komal-sharma-2712** [comment]
I have checked again after new changes, now data is updated properly:

**Data give like this:**

```
{
    "sku": "simple-api-side-3",
    "url_key": "prod-24-api-side",
    "short_description": "Short-desc-from-api-side",
    "description": "desc-from-api-side",
    "name": "Simple Product 24 from admin api side",
    "tax_category_id": null,
    "price": "700",
    "weight": "450",
    "height": "580",
    "width": "500",
    "length": "400",
    "color": "black",
    "size": "XL",
    "brand": "puma",
    "product_number": "17",
    "meta_title": "meta-title-from-api-side",
    "meta_description": "meta-desc-from-api-side",
    "meta_keywords": "meta-keyword-api-side",
    "cost": "900",
    "special_price": "600",
    "special_price_from": "2024-01-05",
    "special_price_to": "2024-01-27",
    "new": "1",
    "featured": "1",
    "visible_individually": "1",
    "status": "1",
    "guest_checkout": "1",
    "channel": "default",
    "locale": "en"
}
```

After that product updated successfully with data updates on admin panel:

![Screenshot from 2024-01-11 16-38-35](https://github.com/bagisto/rest-api/assets/63539748/92048f51-4dbc-4af1-bdb8-5d03ee04af46)

![Screenshot from 2024-01-11 16-34-14](https://github.com/bagisto/rest-api/assets/63539748/f88fd0dc-7cf7-47e1-bde7-66c6b4ee0df1)

So, I am closing this issue.

**Comment by Komal-sharma-2712** [comment]
I have checked new changes, at this moment product update api works fine with update the fields from api postman side.
So, I am closing this issue.

![Screenshot from 2024-01-24 11-13-00](https://github.com/bagisto/rest-api/assets/63539748/23e1ac28-8400-4157-8cb6-12b8c1eff36c)
