### ISSUE TITLE
Should be add more options or fields from product update and create api

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#105]
Should be add more options or fields from product update and create api

**How to Reproduce:**

Need to add more field please check the below screenshot:

**images, videos, meta desc, up, cross, related prod. etc.....**

![image](https://github.com/bagisto/rest-api/assets/63539748/5c77881e-37f7-47e7-a91a-51a715e4b9fe)

_Note: This is a suggestion for more fields for product option._

**Comment by amit-webkul** [comment]
@Komal-sharma-2712 

I have checked and found that the given fields are added in the swagger document, and I have also checked the same in Postman and found product update API is working fine.

Please find the recorded video for the [reference](https://webkul.chatwhizz.com/share/view-recording/65e1b046095e2005794f47bb).
