### ISSUE TITLE
When we create a customer using customer create api side so here should be shown a validation message for phone number parameter field and also should be send an email

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#107]
When we create a customer using customer create api side so here should be shown a validation message for phone number parameter field and also should be send an email.

**How to Reproduce:**

Step 1: Open postman and add a request for create a customer api like this:

```
Method: POST

URL: http://localhost/bg-rest-api-2.0/public/api/v1/admin/customers

Parameter: 
first_name *
string

last_name *
string

email *
string

gender *
string

date_of_birth
string($date)
Customer's date of birth i.e. yyyy-mm-dd

phone
integer

customer_group_id *
integer

```

![Screenshot from 2023-11-27 13-00-47](https://github.com/bagisto/rest-api/assets/63539748/066c71be-be47-4322-9c0f-3ff6dc93523e)

**Issue 1:**

Now hit this request and here shows an error like this:

![Screenshot from 2023-11-27 12-46-21](https://github.com/bagisto/rest-api/assets/63539748/20a5de67-da9f-4b52-a3ae-0d693e7b869c)

**Issue 2:**

Here should be shown a **validation** **message** in **phone** field like admin panel:

![Screenshot from 2023-11-27 12-57-21](https://github.com/bagisto/rest-api/assets/63539748/51d3fefb-25b5-4501-95c8-371ad5ec8dfc)

**Possible Solution:**

- Should be shown a **proper message** after created customer from postman api side and also sends email
 
- Should be shown a **validation** **message** in **phone** field like admin panel

**Comment by Komal-sharma-2712** [comment]
I have checked with new commits changes here now showing a **validation msg for phone params** like this:

![Screenshot from 2024-01-08 18-55-43](https://github.com/bagisto/rest-api/assets/63539748/db3c62b3-e1f1-4725-9367-970876904bae)

But **email notification** issue still exist, need to check this issue also:

![Screenshot from 2024-01-08 19-33-55](https://github.com/bagisto/rest-api/assets/63539748/cf45f56b-860b-4eeb-9c0b-49bd9aca13c8)

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 13-40-34](https://github.com/bagisto/rest-api/assets/154529004/c24e27e5-4a65-44ff-aecd-c57d29045f26)

**Comment by Komal-sharma-2712** [comment]
Now email notification issue not showing when we create customer from api side. So  am closing this issue.

**Comment by Komal-sharma-2712** [comment]
I have checked this issue again, but **phone no validation** is not working fine:

![Screenshot from 2024-01-24 13-34-42](https://github.com/bagisto/rest-api/assets/63539748/e7f7e8f0-7b34-4bde-aadb-24ec30c50f3c)

Also, need to fix the **dob field validation**, should not be add dob date any future date.

![Screenshot from 2024-01-24 13-34-51](https://github.com/bagisto/rest-api/assets/63539748/430c7e1c-2657-48b1-94c3-48067dfd24c4)

**Comment by Komal-sharma-2712** [comment]
I have checked now both validation works fine phone no and dob field:

![Screenshot from 2024-01-25 19-31-23](https://github.com/bagisto/rest-api/assets/63539748/939d342b-39be-4b95-a4f2-5d8297373619)

![Screenshot from 2024-01-25 19-32-55](https://github.com/bagisto/rest-api/assets/63539748/1f0e19ed-bd08-4908-8747-15cf28f1f10a)

Issue FIxed.
