### ISSUE TITLE
Need to add an api for mass update in customer api 

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#108]
Need to add an api for mass update in customer api 

**How To Reproduce:**

Need to add mass update api in customer option api key like others options:

![image](https://github.com/bagisto/rest-api/assets/63539748/9bb69667-6e4b-44f1-ad10-6cb421176812)

**Possible Solution:**

Should be add a api like mass-destroy api

```
Method: Post

URL: [/api/v1/admin/customers/mass-destroy]

Parameters: Add indexes field with an array format here and also value (for status on [1] or off [0] ) with integers value
```

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-10 10-52-31](https://github.com/bagisto/rest-api/assets/154529004/32945d88-1901-4e5a-9552-7747291ce503)

**Comment by Komal-sharma-2712** [comment]
I have checked but not added of mass update customer api:

![Screenshot from 2024-01-24 13-39-56](https://github.com/bagisto/rest-api/assets/63539748/f1f3b0f7-e451-4016-8b94-49a6cc10bcba)

**Comment by Komal-sharma-2712** [comment]
I have checked after new commits now this issue has been resolved.

**Need to add data like this:**

```
{
"indices":[7,8],
"value":1
}
```

![Screenshot from 2024-02-01 17-31-24](https://github.com/bagisto/rest-api/assets/63539748/a5b4537c-84ef-41bb-a52f-ac23220ffb32)

So, I am closing this issue.
