### ISSUE TITLE
Need to be add a create review api also here like others api's

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#109]
**Suggestion:**

Need to be add a create review api also here like others api's

![image](https://github.com/bagisto/rest-api/assets/63539748/7d1f3c05-748e-4e24-9f80-cbb147402bb4)

**Comment by himani-webkul** [comment]
Invalid.

**Comment by Komal-sharma-2712** [comment]
Closed because from admin end, we are not craete reviews for customer
