### ISSUE TITLE
Get Address API, if no address found in customer profile. Message should appear.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#11]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we check the API after customer authorisation and we check the address related information, if there is no address added in the customer profile, then there we can see No message appears in the Postman response.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customers -> Addressed -> All addresses -> Now check the response.
**2.** There we can see null data but no message. Here message need to be added.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-11-30 13-09-11](https://user-images.githubusercontent.com/92721837/204738427-0e38113a-47ff-49a9-8f7d-b2537c125a4f.png)

**Expected Result**

If there are no address in the customer profile, In postman response we can add message.
**Message - No Address Found**

**Comment by vivek-webkul** [comment]
Closing this issue as invalid.
