### ISSUE TITLE
In Customer reviews -> mass update api, reviews status not updated properly on admin panel

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#111]
In Customer reviews -> mass update api, reviews status not updated properly on admin panel

**How to Reproduce:**

Step 1: Open Postman and add a request for **mass update api** like this then hit:

![Screenshot from 2023-11-27 15-47-26](https://github.com/bagisto/rest-api/assets/63539748/1977e1f9-8504-4e02-8ef5-8203f8903cd4)

Here shows a successfully updated message but not updated on admin panel:

`"message": "Selected reviews successfully updated."`

**On Admin Panel:**

![image](https://github.com/bagisto/rest-api/assets/63539748/dc09c26a-fe88-4132-af47-c03ff681a27b)

**Possible Solution:**

Should not be shown default message in every cases, Also should be update reviews on admin panel

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 13-28-00](https://github.com/bagisto/rest-api/assets/154529004/086496d6-96f2-4549-88ea-c97886528f25)
![Screenshot from 2024-01-09 13-27-56](https://github.com/bagisto/rest-api/assets/154529004/c530dacd-5675-4203-a86d-37bab353fed6)
![Screenshot from 2024-01-09 13-27-47](https://github.com/bagisto/rest-api/assets/154529004/1b5b6003-b1eb-4ab5-8fea-519f8913b431)

**Comment by Komal-sharma-2712** [comment]
I have checked this issue now fixed:

![Screenshot from 2024-01-09 18-58-13](https://github.com/bagisto/rest-api/assets/63539748/bc77ed1e-2011-4b3e-85b7-aca9d2ecf8fa)

![Screenshot from 2024-01-09 19-00-12](https://github.com/bagisto/rest-api/assets/63539748/9d95b6fa-caa1-48e5-8110-a9d4efd2ea18)

So closing this issue.
