### ISSUE TITLE
In Customer Review -> update review api, here shows a successfully updated message but not updated

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#112]
In Customer Review -> update review api, here shows a successfully updated message but not updated

**How to Reproduce:**

Open Postman and add a request for **customer review update** api like this then hit:

![Screenshot from 2023-11-27 15-59-27](https://github.com/bagisto/rest-api/assets/63539748/9847b5fe-9fa3-4574-ab8f-c0346d6bee5e)

Here shows a successfully message without any parameter choose also not updated customer review:

`"message": "Review updated successfully."`

**Possible Solution:**

Should be status updated or edit review of customer review update api. Also, shows a warning message if we have not selected any parameter in form-body

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 13-15-43](https://github.com/bagisto/rest-api/assets/154529004/d6c28d45-fa81-4b44-85c5-635792bbaf04)
![Screenshot from 2024-01-09 13-15-41](https://github.com/bagisto/rest-api/assets/154529004/7e6b2fa5-26a9-4dc8-9ba0-c9e1c155ad02)

**Comment by Komal-sharma-2712** [comment]
I have checked now this issue has been fixed also shows on reviewe on customer panel:

![Screenshot from 2024-01-09 17-21-28](https://github.com/bagisto/rest-api/assets/63539748/64502e93-daef-4308-b86a-38e70335c531)

![Screenshot from 2024-01-09 17-20-28](https://github.com/bagisto/rest-api/assets/63539748/98bdd747-dca4-4ddf-9b57-2da46604899d)

So i am closing this issue
