### ISSUE TITLE
In Attribute Families -> Create attribute family api, created successfully but on admin panel view this attribute family so here not showing main and right column details

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#113]
In Attribute Families -> Create attribute family api, created successfully but on admin panel view this attribute family so here not showing main and right column details

**How to Reproduce:**

Step 1: Open a postman and add a request for create attribute family api like this:

![Screenshot from 2023-11-27 16-57-50](https://github.com/bagisto/rest-api/assets/63539748/fdbcfa95-f001-4661-a774-d5533a9b31e0)

After hit this API then shows successfully created.

Step 2: Now Go to the admin panel and open or edit this attribute family:

![image](https://github.com/bagisto/rest-api/assets/63539748/2a60c204-0402-4f21-9a77-9c7104796e86)

After click on edit option then shows like this here not added a columns and if we add from add group button then shows an error in console not saved successfully:

![image](https://github.com/bagisto/rest-api/assets/63539748/77c0a9da-845e-4e66-ba16-6780a7f5ff7c)

**Possible Solution:**

If we have added a attribute family from postman api side then should be shown correct on admin end

**Comment by Komal-sharma-2712** [comment]
I have checked this issue again, issue has not been fixed.

![Screenshot from 2024-01-05 13-14-49](https://github.com/bagisto/rest-api/assets/63539748/30b74583-dc5e-485e-b5ba-f84b81ffea27)

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 10-16-39](https://github.com/bagisto/rest-api/assets/154529004/eff58cc9-bb15-4918-88cb-fe2d14150406)

Code validation updated.

**Comment by Komal-sharma-2712** [comment]
I have checked this issue after new changes, Now code validation is works fine.

![Screenshot from 2024-01-09 19-05-49](https://github.com/bagisto/rest-api/assets/63539748/9d11e853-e2e5-4820-ae03-a6f3fb1d879d)

But on admin panel this attribute family created successfuly but , when we edit from admin end for add a column in this family then not updated shows an error in console like this, when we clicks on add group button changes:

![Screenshot from 2024-01-09 19-07-10](https://github.com/bagisto/rest-api/assets/63539748/5a046937-6c31-40f9-85d2-aba62ecda98e)

Need to fix this also.

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-19 17-19-54](https://github.com/bagisto/rest-api/assets/154529004/6ef402ae-c4b5-4b34-ac24-362e86cf8d2d)
![Screenshot from 2024-01-19 17-20-35](https://github.com/bagisto/rest-api/assets/154529004/9ccb4386-350a-4aeb-9706-eaa9a8fe8c6d)

**Comment by Komal-sharma-2712** [comment]
In this issue, validation issue works fine. But after edit this att. family not showing any column of right and left. like this:

![image](https://github.com/bagisto/rest-api/assets/63539748/bba02944-3eb5-4f3b-a46e-34029896539c)

**Comment by Komal-sharma-2712** [comment]
I have checked this issue, need to give proper data or params in postman end:

```
{
"code":"furniture",
"name":"Furniture",
"attribute_groups":{
"group_0":{
"name":"General",
"code":"general",
"column":1,
"is_user_defined":0,
"custom_attributes":[
{
"id":1
}
]
},
 
"group_1":{
"name":"Description",
"code":"short_description",
"column":2,
"is_user_defined":0,
"custom_attributes":[
{
"id":9
}
]
}
}
}
```

After that att. family created on admin end and also changed successfully, if admin update the att. family.

So, i am closing this issue.
