### ISSUE TITLE
In CMS Page -> Create CMS page then shows an error but created cms-pages on admin end

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#114]
In CMS Page -> Create CMS page then shows an error but created cms-pages on admin end

**How to Reproduce:**

Step 1: Go to the postman and add a request to create cms pages like this:

![Screenshot from 2023-11-27 18-19-49](https://github.com/bagisto/rest-api/assets/63539748/f12051df-0a0b-4806-92d7-6c33dd0dd619)

After hit this request shows an error like this:
`
"message": "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`bg-rest-api-2.0`.`cms_page_channels`, CONSTRAINT `cms_page_channels_channel_id_foreign` FOREIGN KEY (`channel_id`) REFERENCES `channels` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `cms_page_channels` (`channel_id`, `cms_page_id`) values (Default, 15))",
`

Step 2: Now go to the admin panel and page refresh but here cms page created:

![image](https://github.com/bagisto/rest-api/assets/63539748/060a274d-9c85-4094-916f-2a86254dfa71)

**Possible Solution:**

Should be showing a proper message when we create cms page using postman api side

**Comment by Komal-sharma-2712** [comment]
I have checked after some changes now shows this error like this:

`Target class [Webkul\\CMS\\Repositories\\PageRepository] does not exist.`

![Screenshot from 2024-01-09 10-36-34](https://github.com/bagisto/rest-api/assets/63539748/4b754b22-8ad8-45b5-a634-dc51eacbfc2e)


Now again some changes regarding himani side, need to changes in the below path:

**`vendor/bagisto/rest-api/src/Http/Controllers/V1/Admin/CMS/PageController.php`**

> use Webkul\CMS\Repositories\PageRepository;

to 

> use Webkul\CMS\Repositories\CmsRepository;

and

> return PageRepository::class;

to

> return CmsRepository::class;

After that check now create cms page successfully without any error.

**=> 2nd Issue:   With Update API:**

Also, issue in update api that issue also fix. Now update api also works fine after some changes in the below commit:

https://github.com/bagisto/rest-api/pull/141/commits/71716fde432a10e8730c45cae79d76501149500d

So , I am closing this issue for now,.

**Comment by himani-webkul** [comment]
invalid issue.
