### ISSUE TITLE
When we using customer api of register of customer then shows an error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#118]
When we using customer api of register of customer then shows an error

**How to Reproduce:**

Step 1: Go to the postman and add an api for **customer register** api like this:

![Screenshot from 2023-12-12 11-23-38](https://github.com/bagisto/rest-api/assets/63539748/256f4bf9-2e90-4baf-b7ee-0270c580201f)

Add fname, lastname, email, and password parameter then hit.

Step 2: Now after hit request then here shows a warning for **confimation** **password** filed:

`"message": "The password confirmation does not match."`

Step 3: Now check on the web customer panel here **confirmation password** field is required so we will need to add validation for confirmation password field.

**Possible Solution:**

Should be required field of confirmation password field on postman side.

![Screenshot from 2023-12-12 11-20-37](https://github.com/bagisto/rest-api/assets/63539748/8f6de6c4-3542-41b9-b46b-fcf75f0b6dee)

**Comment by Komal-sharma-2712** [comment]
In this Issue, still not showing a **confirmation password parameter** in front like others parameters:
 **"fname, lastname, email, and password parameter"**

![Screenshot from 2024-01-03 12-50-24](https://github.com/bagisto/rest-api/assets/63539748/efa108b1-3f01-4cd6-9272-d5726e7edfcc)

But we have added a par. of confirmation pass like this then request hit so user created successfully: **password_confirmation**

Should be added confirmation field also shown with these fields with validation also.

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 12-50-05](https://github.com/bagisto/rest-api/assets/154529004/ad95cecc-bad5-4c93-a1b0-7947b2822b4f)

**Comment by Komal-sharma-2712** [comment]
I have checked after new changes now confirmation password field shows in required option:

![Screenshot from 2024-01-10 15-53-00](https://github.com/bagisto/rest-api/assets/63539748/4cc79555-12fc-42b8-bd1c-cd4dbe81c91d)

Also, customer registration is successfully:

![Screenshot from 2024-01-10 15-55-38](https://github.com/bagisto/rest-api/assets/63539748/f4890c07-613b-4268-8507-4e34e809efde)


So, I am closing this issue.

**Comment by shivendra-webkul** [comment]
@Komal-sharma-2712 Now It is working as expected please check again.
![customer registration](https://github.com/bagisto/rest-api/assets/121868701/89802e39-ff3e-44c3-bbff-d71ee59cb32e)

**Comment by Komal-sharma-2712** [comment]
I have checked this fixed with confirmation pass field added manually and now works fine without any error. 

But **Need to add this confirmation pass**. field is required like customer panel.

![image](https://github.com/bagisto/rest-api/assets/63539748/15e40659-2cea-496c-a189-3526c257b08a)

**Comment by Komal-sharma-2712** [comment]
Fixed, now confirmation password field is showing in required params:

![Screenshot from 2024-01-31 19-20-01](https://github.com/bagisto/rest-api/assets/63539748/606d938f-a385-472d-a23a-2351156b11ee)
