### ISSUE TITLE
When we using customer api of forgot-password api then shows an error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#119]
When we using customer api of forgot-password api then shows an error

**How to Reproduce:**

Step 1: Go to the **postman** and add an api for **customer forgot-password** api like this:

![Screenshot from 2023-12-12 11-51-21](https://github.com/bagisto/rest-api/assets/63539748/cfdc2a7a-23b8-4ea7-a341-e0bd08561786)

Step 2: After add an email then hit so here shows an error like this:

`"message": "Class \"Webkul\\Customer\\Models\\ResetPasswordNotification\" not found"
`

Then again hit shows like this message. After that try some time then shows again not found error:
```

{
    "message": "Please wait before retrying."
}
```

![Screenshot from 2023-12-12 11-57-53](https://github.com/bagisto/rest-api/assets/63539748/7195def7-2b7a-4c17-b153-97e11152b08f)

**Possible Solution:**

If we have do forgot password api then should be pass change without any error

**Comment by Komal-sharma-2712** [comment]
I have checked this issue has not been fixed, still facing the same error.

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 12-42-12](https://github.com/bagisto/rest-api/assets/154529004/02b3a680-d957-43ea-a01c-0cb8dc0805fe)

**Comment by Komal-sharma-2712** [comment]
I have also checked but issue is still exist.

![Screenshot from 2024-01-10 16-08-05](https://github.com/bagisto/rest-api/assets/63539748/272241c8-2b8a-48c7-919a-583947e94613)
