### ISSUE TITLE
When we using product get api of customer api then shows an error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#120]
When we using product get api of customer api then shows an error

**How to Reproduce:**

Step 1: Go to the postman side add details of product fetch details api of customer option:

```
GET
/api/v1/products
Get product list for the shop
```

![Screenshot from 2023-12-12 12-05-40](https://github.com/bagisto/rest-api/assets/63539748/4fcfbe98-f3a5-4fae-86a8-f3feaf56a66f)

Step 2: Now after hit then shows an error like this:

`"message": "Call to a member function url() on null"`

Step 3: In product fetching with any specific product id then also shows same error:

```
GET
/api/v1/products/{id}
Get shop product by id	
```

![Screenshot from 2023-12-12 12-05-58](https://github.com/bagisto/rest-api/assets/63539748/db0f8cf0-f5f7-48da-97ab-b79276a841a4)

Step 4: For **additional-information** api also after hit shows blank array like this:
```

{
    "data": []
}
```

**Possible Solution:**

Should be fetch details without any error and also with proper successfully message.

**Comment by himani-webkul** [comment]
![Uploading Screenshot from 2024-01-09 12-17-04.png…]()

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 12-17-04](https://github.com/bagisto/rest-api/assets/154529004/a637bf8b-93e9-4709-a395-d41460dfc274)

**Comment by Komal-sharma-2712** [comment]
I have checked this issue after some changes, now this issue has been resolved:

![Screenshot from 2024-01-10 17-17-56](https://github.com/bagisto/rest-api/assets/63539748/9e575aec-2c16-417c-831e-3a4b15ecded1)

With Additional **api:**

![Screenshot from 2024-01-10 17-17-51](https://github.com/bagisto/rest-api/assets/63539748/0984b40f-2d7d-4bcb-9eb4-0a81cb7f058d)

So, I am closing this issue.
