### ISSUE TITLE
When using the iswishlisted product api in customer documentation then shows an error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#121]
When using the **iswishlisted** product api in customer documentation then shows an error

**How to Reproduce:**

Step 1: Go to the postman and add an api for **iswishlisted** on shop api:

```
GET
/api/v1/products/{product_id}/is-wishlisted
Get product's wishlist status
```

Step 2: After add these details then hit so here shows an error like this:

`"message": "Target class [Webkul\\Customer\\Helpers\\Wishlist] does not exist."`

![Screenshot from 2023-12-12 12-59-20](https://github.com/bagisto/rest-api/assets/63539748/1d19a393-2587-4662-b1c3-1510cecf5416)

**Possible Solution:**

If we have wishlist product from shop api then should be wishlist without any error.

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 13-03-57](https://github.com/bagisto/rest-api/assets/154529004/3bd93e73-3ebe-4bed-a1dc-958958455286)

**Comment by Komal-sharma-2712** [comment]
I have checked this issue, now if product is in wishlist then shows like this:

![Screenshot from 2024-01-10 16-37-10](https://github.com/bagisto/rest-api/assets/63539748/b21765b9-d2e2-4d81-9af4-716358547f27)

So , I am closing this issue.

**Comment by Komal-sharma-2712** [comment]
I have checked again now error shows like this with customer login api:

![Screenshot from 2024-01-24 13-48-18](https://github.com/bagisto/rest-api/assets/63539748/6e804430-e718-4fc8-98d7-c4492cea7bda)

**Comment by Komal-sharma-2712** [comment]
I have checked now this api isnot using in api collections, so i am closing this issue for now.

![Screenshot from 2024-01-25 18-36-02](https://github.com/bagisto/rest-api/assets/63539748/3b96e6f6-7d0c-4428-a6aa-e3c287be049b)
