### ISSUE TITLE
When using the wishlist api of customer api then shows an error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#123]
When using the wishlist api of customer api then shows an error

**How To Reproduce:**

Step 1: Go to the **postman** and add an api for **whislist** on shop api:

```
GET
/api/v1/customer/wishlist
Get customer's wishlist
```

**and** 

```
POST
/api/v1/customer/wishlist/{id}
Add or Remove product to customer's wishlist
```

Step 2: Now hit request then shows an error like this:

`"message": "Call to a member function url() on null",`

**A. Fetch wishlist details:**

![Screenshot from 2023-12-12 15-44-25](https://github.com/bagisto/rest-api/assets/63539748/47fd6d47-453d-45d3-8cbc-59e443981ecb)

**B. Fetch wishlist with specific id:**

![Screenshot from 2023-12-12 15-43-49](https://github.com/bagisto/rest-api/assets/63539748/2ee96884-b30b-4953-a34b-9fdb7c72b783)

**Possible Solution:**

Should be wishlist item without any error.

**Comment by Komal-sharma-2712** [comment]
I have checked this issue has not been fixed, still facing the same error.

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 12-19-53](https://github.com/bagisto/rest-api/assets/154529004/efe3af77-45ca-4067-a424-6a26287baa87)
![Screenshot from 2024-01-09 12-19-50](https://github.com/bagisto/rest-api/assets/154529004/fa3658a4-6e63-4aa3-97b9-d174872065e7)

**Comment by Komal-sharma-2712** [comment]
Now this issue has been resolved now:

![Screenshot from 2024-01-10 15-09-33](https://github.com/bagisto/rest-api/assets/63539748/61c03a8b-a970-41e9-96da-01c337fc3ccd)

So, I am closing this issue.
