### ISSUE TITLE
When using cart api of customer doc, then fetch cart details so here shows an error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#126]
When using cart api of customer doc, then fetch cart details so here shows an error

**How to Reproduce:**

**Issue 1:**

Step 1: Open postman and add a below details for fetching cart details with login any customer:

```
GET
/api/v1/customer/cart
Get customer/guest's cart
```

Step 2: Now hit this request and here shows an error like this:

![Screenshot from 2023-12-12 17-24-46](https://github.com/bagisto/rest-api/assets/63539748/04ea639b-2e9a-44ff-bd3d-4bb8a783aa5c)

Note: 
1. If we have not added any product in cart already then here msg shown null like this:

```
{
    "data": null
}
```

2. If we have product added in cart already then fetch cart details so here shown an exception like this:

`"message": "Call to a member function url() on null",
`

**Issue 2:** 

Step 1: Now add the below mentioned api and add product in the cart using api:

```
POST
/api/v1/customer/cart/add/{productId}
Add product to customer's cart
```

Step 2: Now here shows a quantity and product id then added these details:

![Screenshot from 2023-12-12 17-26-46](https://github.com/bagisto/rest-api/assets/63539748/30183b89-8ab3-4873-95c1-820f44263bd7)

![Screenshot from 2023-12-12 17-27-29](https://github.com/bagisto/rest-api/assets/63539748/17973de7-a19c-4f69-be2b-32b437f2b6a9)

After added both parameter then hit request so here shows an error like this:

![Screenshot from 2023-12-12 17-28-09](https://github.com/bagisto/rest-api/assets/63539748/68879d29-e38b-401a-b42e-c5d53ebb2605)

**Possible Solution:**

Should not be shown any error while we fetch or add to product in cart

**Comment by Komal-sharma-2712** [comment]
I have checked both issues but not fixed:

**Issue 1:**

1. If we have not added any product in cart already then here msg shown null like this:

```
{
    "data": null
}
```

2. If we have product added in cart already then fetch cart details so here also shows ike this instead of exception:

```
{
    "data": null
}
```
_Note: Now in 2nd case not showing an exception but also not showing any data._

Here should be shown a wishlist item data.

**Issue 2:**  **Add product in the cart api:**

Here shows a proper successfully message but this product is not added in a cart, check the once again.

**For References, I have attached a video:**

https://webkul.chatwhizz.com/share/view-recording/659541852883053f3555593a

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 12-18-41](https://github.com/bagisto/rest-api/assets/154529004/88496cc0-007c-4b25-b866-946c7e862117)

**Comment by Komal-sharma-2712** [comment]
Checked but not showing like this, still facing error with login cust shows data null, if we have added a prod in cart:

![Screenshot from 2024-01-10 18-23-23](https://github.com/bagisto/rest-api/assets/63539748/6ea504f3-9233-4dcc-a2ba-1d57c95b8288)

![Screenshot from 2024-01-10 18-23-46](https://github.com/bagisto/rest-api/assets/63539748/4dcccdb1-0844-4f75-9241-9d42f45688e2)

**Also, on customer panel prod. not added in cart:**

![Screenshot from 2024-01-10 18-24-01](https://github.com/bagisto/rest-api/assets/63539748/feab4cb7-5575-454a-bfcc-74a169145f60)

**Comment by himani-webkul** [comment]
Invalid Issue.

**Comment by Komal-sharma-2712** [comment]
I have checked again this issue, now issue point:

1. If we have not added any product in cart already then here msg shown null like this:
{
    "data": null
}

2. If we have product added in cart already then fetch cart details so here shown an exception like this:
"message": "Call to a member function url() on null", 

Need to fix 2no. point.

**Comment by shivendra-webkul** [comment]
@Komal-sharma-2712 I checked this issue and found that issue is appearing from core Bagisto.

**Comment by Komal-sharma-2712** [comment]
I am closing this issue, same issue uploaded [here](https://github.com/bagisto/rest-api/issues/127). Need to check with all cart api's also.
