### ISSUE TITLE
In admin api: Attribute and attribute families api should not be update code and type field data

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#128]
In admin api: Attribute and attribute families api should not be update code and type field data

**How To Reproduce:**

Step 1: Open **Postman** and add a details of **update** api of **attribute** and **attribute families** api:

Issue 1:

```
POST
/api/v1/admin/catalog/attributes/{id}
Update attribute
```

**and** 

Issue 2:

```
POST
/api/v1/admin/catalog/attribute-families/{id}
Update attribute family
```

**Add a URL like this:**
http://localhost/bg-rest-api-2.0/public/api/v1/admin/catalog/attribute-families/6?_method=PUT

**Note: When we using post method instead of put method so we need to add in url in last like this: _?_method=PUT_** 

**For references check the below ss:**

![Screenshot from 2023-12-13 11-25-33](https://github.com/bagisto/rest-api/assets/63539748/afa2b44b-3ad8-4351-9ff7-edd1457b758f)

Step 2: Now hit request and here updated successfully this is correct.

Step 3: Now go to the web **admin** **panel** and here clicks on edit button so here **att. code and att. type fields** not updated:

**Issue 1: On Attribute option"**
 
![image](https://github.com/bagisto/rest-api/assets/63539748/a8ffba19-71ee-4a1f-ab12-f76c37e047c8)

**Issue 2: On Attribute Families:**

![image](https://github.com/bagisto/rest-api/assets/63539748/b724225b-0d47-46c0-8a2b-d56e52e3a696)

**For more understanding check the below video:**

https://webkul.chatwhizz.com/share/view-recording/65794b12a874562e016633ab

**Possible Solution:**

Should not be editable code and name fields from postman api side.

**Comment by Komal-sharma-2712** [comment]
I have checked again this issue after new changes:

**Issue 1:**

Now, In **att. update api** not update **att. code field** but **att. type field still editable from api side**. Need to fixed this also att-type field:

![image](https://github.com/bagisto/rest-api/assets/63539748/a62d5be1-3ce5-4dc1-9c19-5619fb39537f)


**Issue 2:**

Now, In **att. families** api **att-family-code field is not editable from api side**. So this issue has been resolved now.

**Comment by himani-webkul** [comment]
Invalid Issue:- managed from front end side

**Comment by Komal-sharma-2712** [comment]
As per discussed with ashish this issue is more difficult to managed from api side, so now at this moment we are closing this issue.

**Comment by Komal-sharma-2712** [comment]
Issue not fixed with att. code and type fields should not be editable in attribute option. At this moment both fields changed successfully from api side.

In att. families option: code name should not be editable.

**Comment by Komal-sharma-2712** [comment]
In attribute and attribute families api now not change code field. But need to fixed for type field in attribute api:

![Screenshot from 2024-01-25 19-12-49](https://github.com/bagisto/rest-api/assets/63539748/2cac7456-7dcc-4774-a391-6a7a96abb9d5)

![Screenshot from 2024-01-25 19-12-36](https://github.com/bagisto/rest-api/assets/63539748/a3671da6-6366-469e-b744-a465dcf4403d)

**Comment by Komal-sharma-2712** [comment]
I have checked after new changes, now type field can not updated from postman side, shows like this message:

![Screenshot from 2024-01-31 18-53-04](https://github.com/bagisto/rest-api/assets/63539748/989a481e-7abd-4fc8-96f4-e5451234d555)
