### ISSUE TITLE
In Admin api: Categories updated but not updating here shows same warning message regarding fields

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#129]
In Admin api: Categories updated but not updating here shows same warning message regarding fields

**How To Reproduce:**

Step 1: Open postman and add a details regarding categories update api details:

```
PUT
/api/v1/admin/catalog/categories/{id}
Update category
```
![Screenshot from 2023-12-13 12-38-02](https://github.com/bagisto/rest-api/assets/63539748/b776cce4-fb8a-48e7-b5f1-a403e71783f0)

Step 2: Now hit this request here shows a **en.name and en.slug** field we have added both parameters then hit request still shows a same warning message

**Note: I have tried with both post and put method instead of put method so we need to add in url in last like this: _?method=PUT**

**Possible Solution:**

If we have added a parameter then should be updated categories instead of shows still facing the same warning message

**Comment by Komal-sharma-2712** [comment]
I have checked this issue has not been resolved now, still facing the same issue.

![Screenshot from 2024-01-05 15-29-45](https://github.com/bagisto/rest-api/assets/63539748/1dfa62fb-d7ff-447f-ad84-2eef9cc9f3d2)

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-08 14-58-05](https://github.com/bagisto/rest-api/assets/154529004/ab6a36b5-e6ac-48cd-899e-f45259659832)

Invalid issue:- data should be send in above format

**Comment by Komal-sharma-2712** [comment]
Fixed issue:

![Screenshot from 2024-01-09 19-43-04](https://github.com/bagisto/rest-api/assets/63539748/cbb011ba-cadd-4e09-94f0-aff0cb1e08d6)

Closing this issue.
