### ISSUE TITLE
In Admin api: Shipments create api not working fine

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#132]
In Admin api: Shipments create api not working fine

**How To Reproduce:**

Step 1: Open postman and add a details regarding create shipments like this:

```
POST
/api/v1/admin/sales/shipments/{order_id}
Create shipment for an order
```

Step 2: After hit this request shows an error like this:

![Screenshot from 2023-12-13 15-50-16](https://github.com/bagisto/rest-api/assets/63539748/08daad6b-f181-4aa8-a4d1-9f9d48005423)

**Possible Solution:**

When we create shipments from api side then should be shipments created without any error.

**Comment by Komal-sharma-2712** [comment]
I have checked this issue after new changes, at this moment this issue has not been fixed properly.

on admin panel product qty shows already or bydefault so here no nee to add prod. qty:

![image](https://github.com/bagisto/rest-api/assets/63539748/3b96b78a-fb90-4d0e-8e1c-568f5e8c20a9)

But we have create shipments from api side so here add all field with add a prod. qty then prod. qty is not updated on admin panel:   [Added a json like this]

```
{
    "shipment":{
        "carrier_title" : "carrier title added from pm side",
        "track_number" : 27781234567,
        "source" :1,
        "total_qty": 1,
        "items": {
              "1" : {
                  "1" :"1"
            }
        }
    }
}

```

Then check on admin panel here not updated prod. qty field, here shows a **shipment prod. qty with 0** prod:

![image](https://github.com/bagisto/rest-api/assets/63539748/aae7cffe-edcf-4d10-ba7e-c9fc6d9942e2)

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 16-38-50](https://github.com/bagisto/rest-api/assets/154529004/c4d7eae4-ae75-4a29-bbd9-07657e2c00e4)
![Screenshot from 2024-01-09 16-38-30](https://github.com/bagisto/rest-api/assets/154529004/fafbf7fc-b912-432d-88d8-c406a88c85ab)
Invalid Issue.

**Comment by Komal-sharma-2712** [comment]
Fixed issue:

![Screenshot from 2024-01-09 19-31-09](https://github.com/bagisto/rest-api/assets/63539748/fc615a4a-4361-43a1-a96f-8a33e491aaa9)

So, I am closing this issue
