### ISSUE TITLE
In Admin api: Refunds create api not working fine

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#133]
In Admin api: Refunds create api not working fine

**How To Reproduce:**

Step 1: Open postman and add a details regarding create refunds like this:

```
POST
/api/v1/admin/sales/refunds/{order_id}
Create refund for an order
```

Step 2: After hit this request shows an error like this:

![Screenshot from 2023-12-13 15-57-31](https://github.com/bagisto/rest-api/assets/63539748/9aa1c145-f609-414e-8ff2-f97b79de4388)

**Possible Solution:**

When we create refunds from api side then should be refund created without any error.

**Comment by Komal-sharma-2712** [comment]
I have checked after new changes in raw format, now at this moment shows like this message:

```
{
    "message": "We found an invalid quantity for refund items."
} 
```

![Screenshot from 2024-01-05 17-18-45](https://github.com/bagisto/rest-api/assets/63539748/f2d26e78-a0dc-4d9d-87af-b1c17522564a)

**Raw format:**

```
{
    "refund" : {
        "shipping" : {
            "1" : 1
        },
        "adjustment_refund" : "1200", 
        "adjustment_fee" : "100",
        "items" : {
            "1" : 1
        }
}
```

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 14-14-54](https://github.com/bagisto/rest-api/assets/154529004/7064a39e-21e8-43b1-a992-9305a27c7ae1)

**Comment by Komal-sharma-2712** [comment]
I have checked again now refunds created:

![Screenshot from 2024-01-09 19-35-31](https://github.com/bagisto/rest-api/assets/63539748/e62a810e-449c-4fab-abf7-422db6f3ac17)

So I am closing this issue.
