### ISSUE TITLE
In Admin api: When currencies update time here code validation not working like create currencies time add only 3 characters code limit

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#135]
In Admin api: When currencies update time here code validation not working like create currencies time add only 3 characters code limit

**How To Reproduce:**

Step 1: Open postman and add an api details of update currencies like this:

```
POST
/api/v1/admin/settings/currencies/{id}
Update currency
```

Add this in last url: **?_method=PUT** , check the below ss:

![Screenshot from 2023-12-13 16-54-58](https://github.com/bagisto/rest-api/assets/63539748/00c8df32-14ca-4f2f-a922-bf088a6e6ca9)

Step 2: Now hit this request and updated  successfully this request

Step 3: Now add code field more than 3 characters and then send request here added successfully instead of shows a validation message like created currency time and also on web admin panel shows a warning message like this:

**On postman side when we create currencies using api:**

`"message": "The code may not be greater than 3 characters.",`

![Screenshot from 2023-12-13 16-45-14](https://github.com/bagisto/rest-api/assets/63539748/427ddf1f-893b-4aba-835f-08fb6ae82772)

**On admin panel when we create currencies using api:**

![image](https://github.com/bagisto/rest-api/assets/63539748/bae13d38-3296-4fa7-832c-da37e7db2fc3)

**Possible Solution:**

Should be shown a warning on update currency time, when we using update currency api and also on need to update on admin panel.

**Comment by shivendra-webkul** [comment]
@Komal-sharma-2712 It is working fine please check it.
Reference:-![image](https://github.com/bagisto/rest-api/assets/121868701/30df9426-a971-49dc-ba0b-adf0dd9dcf20)

**Comment by Komal-sharma-2712** [comment]
Issue has been fixed, so i am closing this issue.
