### ISSUE TITLE
In Admin api: Exchange Rates api not working properly shows an exception

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#136]
In Admin api: Exchange Rates api not working properly shows an exception

**How To Reproduce:**

**Issue 1:**

Step 1: Open postman and add api for exchanges rates create like this:

```
POST
/api/v1/admin/settings/exchange-rates
Store the exchange rate
```

Step 2: Now hit this request here shows a required parameters and added all parameters then hit so here shows an error like this:

![Screenshot from 2023-12-13 17-14-23](https://github.com/bagisto/rest-api/assets/63539748/57df992f-e6f9-4487-a014-821b07ab90fa)

After added all fields and parameters:

![Screenshot from 2023-12-11 13-59-17](https://github.com/bagisto/rest-api/assets/63539748/0d4a826c-2f02-487c-b0a4-f8a140c99399)

**Issue 2:**

When we **update exchange rates** with post method add in last url **?_method=PUT**, then also shows same error like this:

![Screenshot from 2023-12-13 17-17-02](https://github.com/bagisto/rest-api/assets/63539748/39d80a63-2e8b-4096-a5a9-5c5a6c1ae6f4)

**Possible Solution:**

Should be exchange rates create without any error show like admin panel

**Comment by himani-webkul** [comment]
Send target_currency as currencies_id.
Find the attachment below
![Screenshot from 2024-01-08 13-41-46](https://github.com/bagisto/rest-api/assets/154529004/c18f62c3-3575-4d41-9d32-328605ca455a)
![Screenshot from 2024-01-08 13-39-26](https://github.com/bagisto/rest-api/assets/154529004/912ae1ab-5257-413f-be4e-246ab3d645be)

**Comment by Komal-sharma-2712** [comment]
I have checked this issue with add currencies code id so here works fine with create and update currency api:

![Screenshot from 2024-01-08 16-46-06](https://github.com/bagisto/rest-api/assets/63539748/56879f0a-29f1-47f2-8eae-bf4f77e1a29f)

So now I am closing this issue.

**Comment by shivendra-webkul** [comment]
@Komal-sharma-2712 It is working fine please check it.

**Comment by Komal-sharma-2712** [comment]
I have checked this issue has been resolved now. When create exchange rates api works fine. 

![Screenshot from 2024-01-24 11-57-29](https://github.com/bagisto/rest-api/assets/63539748/ef15ef6f-f0e4-4936-a5fa-f019f5230c4f)


So, I am closing this issue.
