### ISSUE TITLE
In Admin api: Create and Update Inventory source api not added country parameter using postman api

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#137]
In Admin api: Create and Update Inventory source api not added country parameter using postman api

**How To Reproduce:**

Step 1: Open postman and add a details regarding inventory sources like this:

```
POST
/api/v1/admin/settings/inventory-sources
Store the inventory source
```

and 

```
POST
/api/v1/admin/settings/inventory-sources/{id}
Update inventory source
```

Add in last url like this: ?_method=PUT for update data only

Step 2: Here we have added all req. field with country field also and then hit send request here created and updated successfully inventory sources:

![Screenshot from 2023-12-13 17-36-15](https://github.com/bagisto/rest-api/assets/63539748/dbebf53a-0741-4c05-b478-8644abaaff81)

Step 3: Now check on the admin panel and here created and updated successfully but only county field is not updated and also not added country field:

![image](https://github.com/bagisto/rest-api/assets/63539748/65f46f45-61b2-483b-8445-f6df56c95479)

**Possible Solution:**

Should be added a country field if we have added parameter from postman api side

**Comment by himani-webkul** [comment]
Send values as below 
![Screenshot from 2024-01-08 13-35-46](https://github.com/bagisto/rest-api/assets/154529004/9dff82c6-9937-46f9-b959-1a24734ad823)

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-08 13-36-52](https://github.com/bagisto/rest-api/assets/154529004/fc47d964-0613-4124-871a-808ed766cecf)

**Comment by Komal-sharma-2712** [comment]
I have checked same as now country field is added on admin panel:

![image](https://github.com/bagisto/rest-api/assets/63539748/3e12a6fd-f5ba-4e00-9142-b6de10e28575)

But here one more issue left, please check the below points:

1. In Inventory create api is not showing **longitude** **params** value in received data:

![Screenshot from 2024-01-08 13-53-02](https://github.com/bagisto/rest-api/assets/63539748/a02b93c3-741d-4350-8b4d-e3e4a7716de2)

2. In Updated api is not showing **longitude params** value in recieved data:

![Screenshot from 2024-01-08 13-59-30](https://github.com/bagisto/rest-api/assets/63539748/09d6dc17-94c5-49a9-a05a-abd59e9fc555)

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 19-51-13](https://github.com/bagisto/rest-api/assets/154529004/fcd2c546-3655-4376-97f4-0c8eeb8468aa)

**Comment by Komal-sharma-2712** [comment]
I have checked again this issue after some changes, now this issue has been resolved

![Screenshot from 2024-01-10 17-08-57](https://github.com/bagisto/rest-api/assets/63539748/00feb998-0c16-442f-9f4a-a9d92f1cb4d6)

Now showing longitude value also. So, I am closing this issue.

**Comment by Komal-sharma-2712** [comment]
I have checked this issue has been fixed now. So, I am closing this issue.
