### ISSUE TITLE
In Admin api: Roles api created here desc. field should be required like admin panel also permission details not showing when we create roles from postman side

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#138]
In Admin api: Roles api created here desc. field should be required like admin panel also permission details not showing when we create roles from postman side

**How To Reproduce:**

**Issue 1:**

Step 1: Open postman and add a details of role created api like this:

```
POST
/api/v1/admin/settings/roles
Store the role
```

![Screenshot from 2023-12-13 17-59-25](https://github.com/bagisto/rest-api/assets/63539748/60c82caf-d344-463f-8e1f-8a54626996b5)

Step 2: Added a required fields and hit request here showing successfully msg also created a role on admin panel:

![Screenshot from 2023-12-13 17-59-44](https://github.com/bagisto/rest-api/assets/63539748/4fab08d5-6d61-41ab-a099-e903001f2a11)

Step 3: Now check on admin panel here **permissions** not added in this role and also here **description** **field** is req. on admin panel:

![image](https://github.com/bagisto/rest-api/assets/63539748/8b543952-8115-4a9a-a166-15a9d6ab9385)

**Issue 2:**

Add details with update roles api like this:

![Screenshot from 2023-12-13 18-18-02](https://github.com/bagisto/rest-api/assets/63539748/460151f3-e9cb-4e6b-9ed0-22c139e9d11d)

Also here same issue with permission type and desc. field is not req. like created role api.

**Possible Solution:**

Should be added a description field is required from postman api side like admin panel. Also, need to add data in permission type field also.

**Comment by himani-webkul** [comment]
Added description field as required and also for  permission_type have to send value as custom or all.

**Comment by Komal-sharma-2712** [comment]
I have checked after new updates now desc. field is required on create role api. Also, **permission_type** params is works fine with custom and all.

![Screenshot from 2024-01-08 17-46-03](https://github.com/bagisto/rest-api/assets/63539748/3186b4f8-b1fb-4d6d-b678-09b7ddf62192)


So, I am closing this issue.

**Comment by Komal-sharma-2712** [comment]
Fixed issue with validation and created on admin panel:

![Screenshot from 2024-01-25 18-47-40](https://github.com/bagisto/rest-api/assets/63539748/21663793-2273-499d-9585-b51b9c6f7f2d)

**Admin Panel:**

![Screenshot from 2024-01-25 18-48-37](https://github.com/bagisto/rest-api/assets/63539748/ef79de65-80f6-43f2-864b-0c7368feaf52)
