### ISSUE TITLE
In Customer api: Profile update api need to add a validation in first and last name field like admin panel

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#139]
In Customer api: Profile update api need to add a validation in first and last name field like admin panel

**How To Reproduce:**

Step 1: Open postman and add a profile details like this:

![Screenshot from 2023-12-13 18-51-00](https://github.com/bagisto/rest-api/assets/63539748/1131b9a0-8d5f-4526-a3c2-040e12cb3041)

Step 2: Now check on the admin panel and here profile updated successfully

Step 3: Now saved from admin end and here showing in **first and last name and phone no.** field validation msg like  this:

`The first name can only accept alpha, numeric and spaces.`

![Screenshot from 2023-12-13 18-52-15](https://github.com/bagisto/rest-api/assets/63539748/3f952e37-05cb-48aa-88b4-3ae06a26dfdf)

**Possible Solution:**

Should be shown a validation msg, if we are using api for profile update like admin panel. Should be added validation in all field **first and last name and phone no.** field

**Comment by Komal-sharma-2712** [comment]
I have checked this issue has not been fixed properly. At this moment not contains validation in fname, lname, phone-no field.

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-09 17-32-25](https://github.com/bagisto/rest-api/assets/154529004/1f54cb0b-680f-4931-acb9-d4f84c6ebe9a)

**Comment by Komal-sharma-2712** [comment]
I have checked this issue, now resolved with fname, lastname validation:

![Screenshot from 2024-01-10 11-17-21](https://github.com/bagisto/rest-api/assets/63539748/e4da9600-2b91-4b35-a822-0c915b81bce6)

But one field are left **phone** no field also need to add a validation here

**Comment by Komal-sharma-2712** [comment]
I have checked again after new changes so phone no is shows a validatoion also:

![Screenshot from 2024-01-10 11-39-06](https://github.com/bagisto/rest-api/assets/63539748/17f09465-32ad-42a8-bfb1-1db8e36a6b02)

So I am closing this issue.

**Comment by Komal-sharma-2712** [comment]
I have checked this issue, validation works only on fname and lname. But not working on phone no need to fixed this also.

Before commit id for phone no this:

https://github.com/himani-webkul/rest-api/commit/930f3f067f96322c44451aad4a1e4e45972b9b84#diff-34771883e7ca1d8547925657338c9b9a6f46ef34baa2ed08bcf8f804fa5db442R146

But after merge PR commit id this:

https://github.com/bagisto/rest-api/commit/3f658147d58c686c3a54fb30f378cb0ef5903f8e

**Comment by Komal-sharma-2712** [comment]
Fixed with phone no. also:

![Screenshot from 2024-01-25 18-25-41](https://github.com/bagisto/rest-api/assets/63539748/44a91107-f44d-40df-965e-2668459bf768)

So, I am closing this issue.
