### ISSUE TITLE
Add Simple Product to Cart - API is having Product ID check issue. 

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#14]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we pass **product** id in the **URL** and **same** ID when we use to the **form data**, it is working fine, but when we check **replace the URL product ID** with **another product**, there we can see the in **front end and API response**.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customer -> Cart -> Add simple product to Cart
**2.** Use Simple product ID in the URL and then in Form Data product ID use another simple product ID.
**3.** Now in API we can see the issue.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.
**Issue** which is **detected** is that, it **replaced** the **Product** with **another product** and **QTY** is also **increased**. **It replaced the product with the ID which is passed in the URL.**

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/204808911-72f0dc4c-6216-4879-8749-33bce830fe66.mp4

**Expected Result**

The **Product ID check** should be **applied** so that the **URL** based **product ID** should be **updated**.

**Comment by amit-webkul** [comment]
Here, 
I am unable to understand about issue,
Please again share the screen shot / video of the issue.

**Comment by Amitk-webkul** [comment]
@amit-webkul While adding multiple products but it is adding only one product and increasing the quantity of the newly added product.

**Comment by Amitk-webkul** [comment]
Now it is working fine. [Here](https://tinyurl.com/2nuycf6r)
