### ISSUE TITLE
Cart and Checkout api's, should be worked without login any customer (Guest user) also, at this moment guest user not add prod. in cart and also checkout using api

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#140]
Cart and Checkout api's, should be worked without login any customer (Guest user) also, at this moment guest user not able to add prod. in cart and also checkout using api.

**How To Reproduce:**

Step 1: Open postman and add a details of **cart and checkout api** but here not added any customer login details or any token here just details add and then hit after that shows like this:

```
POST
/api/v1/customer/cart/add/{productId}
Add product to customer's cart	
```

```
{
    "error": "Oops! Looks like you're not allowed to access this page. It seems you're missing the necessary credentials."
}
```

![Screenshot from 2023-12-14 13-00-37](https://github.com/bagisto/rest-api/assets/63539748/92fd6f59-0d55-48ea-beef-3c948b066b4f)

Step 2: Same as **checkout api** time here added a **save address api** without login any customer details so here shows a **customer login page instead of add save address like web guest user account**:

```
POST
/api/v1/customer/checkout/save-address
Save addresses at the checkout
```

![Screenshot from 2023-12-14 13-03-10](https://github.com/bagisto/rest-api/assets/63539748/229e6f6e-ef61-4e4a-9cdd-9ffaeb1cf5c9)

**Possible Solution:**

- If we have added a product in cart using without login any cust so should be added a prod. in cart

- If we have added a address while checkout without login any cust then should be added a address in checkout time

**Comment by Komal-sharma-2712** [comment]
I have checked this issue has not been fixed properly. With customer and guest user also not working.
Only shows a successfully message but product not added, removed in cart or address.

Check the below video:

https://webkul.chatwhizz.com/share/view-recording/65954d8b2883053f35558205

Need to check once again all api's of cart and checkout api's

**Comment by himani-webkul** [comment]
Cart and Checkout API working with or without customer login.

**Comment by Komal-sharma-2712** [comment]
I have checked but not working, please check the once again. Also, with loign customer shows data value null, when we add a items in cart.

![Screenshot from 2024-01-10 11-35-38](https://github.com/bagisto/rest-api/assets/63539748/1aacd236-259c-4826-be23-62710ca69695)

**Comment by himani-webkul** [comment]
No feature for guest checkout in rest-api. Invalid issue.

**Comment by devansh-webkul** [comment]
Hi @Komal-sharma-2712,

We don't provide guest features in rest-apis.
