### ISSUE TITLE
When we using the inventory update api then inventory not updated

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#142]
When we using the inventory update api then inventory not updated

**How To Reproduce:**

Step 1: Go to Postman and add an api's like this:

```
POST
/api/v1/admin/catalog/products/{id}/inventories

Update the catalog product's inventory	
```

Step 2: Now here shows only msg without any parameters added here:

![Screenshot from 2024-01-03 12-05-42](https://github.com/bagisto/rest-api/assets/63539748/e93119be-505d-4c58-84fc-0ccdd9a991f8)

Here only shows a added inventory data from admin UI side. But not updated inventory from api side.

**Possible Solution:**

Should be update inventories data from postman api side

**Comment by Komal-sharma-2712** [comment]
I have checked this issue, now fixed:

Add  a data like this in json form:

```
{
  "inventories": {
    "1": 270
  }
}
```

![Screenshot from 2024-01-09 18-29-54](https://github.com/bagisto/rest-api/assets/63539748/a7b7a06b-c862-4889-aefd-54c59fd41ff1)

On admin **panel:**

![Screenshot from 2024-01-09 18-30-00](https://github.com/bagisto/rest-api/assets/63539748/9b877002-5e2f-4990-abcb-87667abeed1b)

So, I am closing this issue

**Comment by Komal-sharma-2712** [comment]
I have checked again, now this issue has not been fixed shows like this error:

"message": "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`rest2-api-2.0`.`product_inventories`, CONSTRAINT `product_inventories_inventory_source_id_foreign` FOREIGN KEY (`inventory_source_id`) REFERENCES `inventory_sources` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `product_inventories` (`product_id`, `inventory_source_id`, `vendor_id`, `qty`) values (2, 0, 0, 7))"

![Screenshot from 2024-01-23 16-09-51](https://github.com/bagisto/rest-api/assets/63539748/92a22f54-973c-4dba-9797-f25e76f65d29)

Need to check this issue again.

**Comment by shivendra-webkul** [comment]
@Komal-sharma-2712 I have checked  this issue and found it is working fine you need to enter inventory properly 
for examople:-
{
  "inventories": {
    "1": 270
  }
}

![image](https://github.com/bagisto/rest-api/assets/121868701/7de09c53-0527-4bbd-9244-2e3271af576a)

**Comment by Komal-sharma-2712** [comment]
Closed need to add correct data when we update inventory from postman.

![Screenshot from 2024-01-30 11-49-41](https://github.com/bagisto/rest-api/assets/63539748/761967fd-1ca2-49a7-9e05-bace86aeb819)

![Screenshot from 2024-01-30 11-49-53](https://github.com/bagisto/rest-api/assets/63539748/6f9ce151-d3f0-4527-9a6d-ff4bc1fd8cba)
