### ISSUE TITLE
When we create new categories from api side then not created new category

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#144]
When we create new categories from api side then not created new category

**How To Reproduce:**

Go to the postman api side and add here api for create new category like this:

Add these parameters then hit:

- name
- slug

Here shows a warning msg like this:

```
"message": "This slug is getting used in either categories or products.",
    "errors": {
        "slug": [
            "This slug is getting used in either categories or products."
        ]
    }

```

![Screenshot from 2024-01-05 15-37-00](https://github.com/bagisto/rest-api/assets/63539748/ef2d0a2e-1a7e-4ef0-8129-5c24e95a2a5b)

**Possible Solution:**

If we have add a category from pm api side then should be created category without any shows error.

**Comment by Komal-sharma-2712** [comment]
Fixed this issue:

![Screenshot from 2024-01-09 17-47-10](https://github.com/bagisto/rest-api/assets/63539748/79d81eb9-a4df-45d7-aeef-2beda2037e33)

_Note: After visible in front end we will choose this category in root category from admin end._

So, i am closing this issue.

![Screenshot from 2024-01-09 17-52-43](https://github.com/bagisto/rest-api/assets/63539748/f5c948d6-dd9b-4677-addb-3f06ec1f1385)

**Comment by himani-webkul** [comment]
Invalid issue
