### ISSUE TITLE
Cart and Catalog rule update api: In Parameter (sort_order) is not updated in get details after update successfull

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#147]
Cart and Catalog rule update api: In Parameter (sort_order) is not updated in get details after update successfull

**How To Reproduce:**

Step 1: Go to the postman and add a details for catalog update like this:

**Catalog Rule:**

```
{
    "name" : "Catalog Rule from api side #2",
    "description": "Added a desc.-from-api-side",
    "channels" : [1],
    "coupon_type": 0,
    "customer_groups" : [1,2],
    "action_type" : "by_percent",
    "discount_amount" : 50,
    "status": 1,
    "starts_from": "2024-01-08",
    "ends_till": "2024-01-28",
    "sort_order": "1"
}
```

_and_

**Cart Rule:** 
{
    "name" : "Edit-again-Cart-rule-create-from-api-side-with-15-%",
    "description": "Edit Added a desc from api: Cart-rule-create-from-api-side-with-15-%",
    "channels" : [1],
    "coupon_type": 0,
    "customer_groups" : [1,2],
    "action_type" : "by_percent",
    "discount_amount" : 15,
    "status": "1",
    "sort_order": "1"
}

After hit this request updated successfully but in given data **sort_order** value shows still **0** here:

```
{
    "data": {
        "id": 3,
        "name": "Edit-Catalog Rule from api side",
        "description": "Edit-Added a desc.-from-api-side",
        "starts_from": "2024-01-08",
        "ends_till": "2024-01-28",
        "status": 1,
        "condition_type": 1,
        "conditions": [],
        "end_other_rules": 0,
        "action_type": "by_percent",
        "discount_amount": "50.0000",
        "sort_order": 0,
        "created_at": "2024-01-08T06:39:41.000000Z",
        "updated_at": "2024-01-08T07:29:27.000000Z"
    },
    "message": "Catalog rule updated successfully."
}

```

![Screenshot from 2024-01-08 13-14-50](https://github.com/bagisto/rest-api/assets/63539748/43929d1e-4e9b-440c-baf0-4c256ad1bba7)

![Screenshot from 2024-01-08 13-18-01](https://github.com/bagisto/rest-api/assets/63539748/c0019af5-b07a-4b13-b434-d6f48f96885f)

**Possible Solution:**

Should be **sort_order** value visible in received data.

**Comment by himani-webkul** [comment]
On double click the data is getting updated.

**Comment by Komal-sharma-2712** [comment]
As per discussed with himani and ashish for this sort_order paraamater this works with the double clicks. This is correct, So i am closing this issue for now.
