### ISSUE TITLE
Add API for Booking Products.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#15]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When checking the Add to cart API, there it was found that the Booking Product API is missing. Please add the API for Booking Product and there types.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customer -> Cart
**2.** there we cannot see the API related to Booking Product.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-12-01 11-49-58](https://user-images.githubusercontent.com/92721837/204980200-40fbaeb6-b897-4d19-af11-170bd3080803.png)

**Expected Result**
There should be API for the booking product, we have different Booking Products, for each we should have API.
1. Default Booking
2. Appointment Booking
3. Event Booking
4. Table Booking
5. Rental Booking.

**Comment by amit-webkul** [comment]
@Amitk-webkul , I have added the endpoint for booking product, Now it will working fine .

**Comment by Komal-sharma-2712** [comment]
We are closing this issue for now, because booking product option is not available in v2.0
