### ISSUE TITLE
Customer API -> Cancel order Api not working properly

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#154]
Customer API -> Cancel order Api not working properly

**How to Reproduce:**

Step 1: Go to the postman and add a api like this:

```
POST
[/api/v1/customer/orders/{id}/cancel]
Cancel customer's order by id
```

Step 2: Now after hit this request shows an exception like this:

"message": "Call to undefined method Webkul\\Customer\\Models\\Customer::all_orders()",

![Screenshot from 2024-01-10 18-51-32](https://github.com/bagisto/rest-api/assets/63539748/9793df5e-fc49-4d6d-9efd-c70813509db6)

**Possible Solution:**

Should be order cancel without any error.

**Comment by devansh-webkul** [comment]
@Komal-sharma-2712,

I think this issue is already fixed by Antu.
