### ISSUE TITLE
Customer API -> Categories -> Descedent-cat. api shows an error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/rest-api#159]
Customer API -> Categories -> Descedent-cat. api shows an error

**How to Reproduce:**

Step 1: Go to the postman and add a api like this:

```
GET
[/api/v1/descendant-categories]
Get shop descendant categories
```

Step 2: After hit this request shown an error like this:

![Screenshot from 2024-01-10 19-31-00](https://github.com/bagisto/rest-api/assets/63539748/c5d6d331-4f07-479a-b881-e36d99e16c82)

**Possible Solution:**

Should be shown a proper category after hit request

**Comment by himani-webkul** [comment]
![Screenshot from 2024-01-16 10-06-24](https://github.com/bagisto/rest-api/assets/154529004/30b01e4a-3d25-4cc9-8561-b6811f2fab54)
invalid issue
