### ISSUE TITLE
Add Group Product in Cart is having issue in adding product.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#16]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we add simpler products with the help of group product and simple product id, we are able to add those products in the cart which are not related to the Group.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customers -> Cart -> Adding Group Product to Cart.
**2.** There when we pass the ID of the simple product which is not in the product, we can add the product to the cart.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/205025103-3db7d243-8933-4499-8660-86c90321433f.mp4

**Expected Result**
Here product adding check should be applied. No other product accept the group simple product should be added.

**Comment by Amitk-webkul** [comment]
If the grouped product has multi-products so only add single products instead of multiple products.

**Comment by Amitk-webkul** [comment]
I have found the correct details in the collection now it is working fine.
