### ISSUE TITLE
We are able to update the QTY of downloadable product with Update Cart Item API.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#17]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
We are able to  update the QTY of the Downloadable product. when we pass the Product ID of Downloadable product.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customers  -> Cart -> Update Cart.
**2.** Pass the ID for Downloadable Product.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/205035915-4e937cc1-a255-4f4e-b401-7b4195a9f4a3.mp4

**Expected Result**
Here the ID should not pass and a message should appear.
**Product Quantity cannot be Updated.**

**Comment by ashishkumar-webkul** [comment]
Same concern when we checked for the bundle and group product, there we can see the 200OK message is appearing but nothing is happening.
There should be a proper message and the API should not pass.

**Product Quantity cannot be Updated.** of **Cannot Update Bundle or Booking Product.**

**Comment by Amitk-webkul** [comment]
Able to update the Product quantity. [Here](https://tinyurl.com/2may9zk2)

**Comment by Amitk-webkul** [comment]
Now it is working fine.[Here](https://tinyurl.com/2eewq9zy)
