### ISSUE TITLE
Update Cart Items API is not working.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#18]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
After adding the product id of the product which is already in the cart, if we increase the qty and decrease the qty and try to update the product with API, we are getting 200OK response but it is not working.

**Steps to Reproduce**
**1.**  Go to Postman -> Shop -> Customers -> Cart -> Update Cart.
**2.** Now pass the ID of the product which is already added in the Cart.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/205040445-df5be763-6cbc-4e9d-8b39-82fd30474544.mp4

**Expected Result**
If we are updating a product that means it should respond and send the correct information.

**Comment by amit-webkul** [comment]
Also Updates added in API collection

**Comment by amit-webkul** [comment]
Shared through the Mail

**Comment by Amitk-webkul** [comment]
@amit-webkul not fixed. it is showing an error in response. [Here](https://tinyurl.com/2nyzutol)

**Comment by Amitk-webkul** [comment]
@amit-webkul The exception is fixed but changes are not [reflected](https://tinyurl.com/2ekfy46m).

**Comment by Amitk-webkul** [comment]
Now it is working fine. [Here](https://tinyurl.com/2j9nyrob)
