### ISSUE TITLE
Remove Coupon API Message to be Updated.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#19]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we remove the Coupon which is applied to the cart, after the API is hit we can see the message is in code text. Please add a proper text.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customer -> Cart -> Remove Coupon

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-12-01 17-40-12](https://user-images.githubusercontent.com/92721837/205050067-4ee63052-d286-4836-9dea-7fd2171816bc.png)

**Expected Result**
Please add proper message -> **Coupon Removed Successfully.**

**Comment by vivek-webkul** [comment]
Closing this issue as already fixed:
[Commit LInk](https://github.com/bagisto/rest-api/commit/2034fd773c15a32c96af5a467f1dbfa223d0bb36)
