### ISSUE TITLE
Save Address API is not working.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#20]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we check the Save address API in postman, there we can see 422 Unprocessable Content, here in the API response we can see that there are certain fields which are missing. which need to be added.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customer -> Shipping. 
**2.** Here we can see that the raw data has some fields missing.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-12-02 16-38-35](https://user-images.githubusercontent.com/92721837/205282122-ae6f705a-becd-4fc5-872d-3237742afb21.png)
![Screenshot from 2022-12-02 16-46-40](https://user-images.githubusercontent.com/92721837/205282133-57899655-59cb-451f-a740-200a5d8f9574.png)

**Expected Result**

Raw Data and Form Data Field which are required here are.
City Name
Phone 
addressid.

**Comment by Amitk-webkul** [comment]
While saving the address. it is showing an exception. [Screenshot](https://tinyurl.com/2z5b9osj)

**Comment by Amitk-webkul** [comment]
Now this is working fine. [Here](https://tinyurl.com/2jgzqvdn)
