### ISSUE TITLE
We are getting same response in the Additional Information (Attributes) API.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#21]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we check the Additional Information (Attributes) API, there we change the product Id, still we are getting the same response. 

**Steps to Reproduce**
**1.** Shop -> Catalog -> Products -> Additional Information (Attributes)
**2.** There in the URL if we change the product ID, still we are getting same response.

**Actual Result**
We can see that every time we can see the ID 25 as a result. Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/205809791-f7a6072c-5bf3-42b5-8a25-f14e5e2b0774.mp4

**Expected Result**
The response should be according to the product Id.

**Comment by Aqib-Webkul** [comment]
As I can check this is also not a issue, the same result was coming as you were checking all the result of configurable products

**Comment by Amitk-webkul** [comment]
This is working fine.
