### ISSUE TITLE
Get Configurable Config API is showing details of all the products.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#22]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we send the ID (Parent ID) of the Configurable Product, there we can see all the information related to the configurable Variants, but when we send the ID of other products then also we can see the Regular Price and Final Price of the product.
Eg. If we add the Virtual Product ID in the URL, we are able to fetch the information. 

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Catalog -> Products -> Get Configurable Config
**2.** Now check the details with Config Product Parent ID, we are able to fetch the details.
**3.** Now check the details of the product like virtual product and other products, here we can see the Regular Price and Final Price.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/205823959-1488d560-6dc5-4f56-87eb-abfb1d879f7f.mp4

**Expected Result**

Here details related to the configurable product and its variants should appear. Other product details should not appear. Message should appear.
**MESSAGE - Product Not Found**

**Comment by Aqib-Webkul** [comment]
This is also not issue of API, we are getting the result in the same way from core.

**Comment by ashishkumar-webkul** [comment]
Checked the concern again and Found that the details are appearing correctly. Hence I am closing the issue as the configurable product details and there variants are appearing correctly. Please check the video for the same.

**Video**

Uploading Config Configurtaions.mp4…
