### ISSUE TITLE
Show Category with ID -> It should not respond without Category ID.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#23]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we check the Show Category with Category ID, there we can see that the Category details are visible, but when we check the Details without Category id, we are able to see all the Category.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Catalog -> Categories - > Show Category by ID.
**2.** Here in URL, do not use the Category id, and then we can fetch all the Categories details.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/205839755-4be18d0a-7877-4888-b63d-10bbfc5634ba.mp4

**Expected Result**
Here only Categories with Category Id should else a message should appear. If we are able to fetch all the products the there is no need of having show all Category API.
**Message - No Category Found or Please add Category ID.**

**Comment by Aqib-Webkul** [comment]
This is not a issue.
If you are requesting url like {{base_url}}/api/v1/categories/1 then it is returning the details according to categories Id.
if requested url is {{base_url}}/api/v1/categories without any categories Id then it is returning all the available categories details.

**Comment by ashishkumar-webkul** [comment]
Checked and found that the issue is working fine. The URL which is hit without the  use of Category ID, is used to fetch all the Categories hence it is working fine. Hence I am closing the issue from here.
Please check the video for the reference.

**Video**

https://user-images.githubusercontent.com/92721837/230077732-e015086e-cd5c-4247-8e0f-c63134f667b1.mp4
