### ISSUE TITLE
Show Product with ID -> It should not respond without Product ID.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#24]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we check the Show Product with product ID, there we can see that the product details are visible, but when we check the Details without the Product without the product id, we are able to see all the products.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Catalog -> Products - > Show Product by ID.
**2.** Here in URL, do not use the product id, and then we can fetch all the products details.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/205829338-439c1244-5169-49a1-ac83-6326b3fb0433.mp4

**Expected Result**
Here only products with Product Id should else a message should appear. If we are able to fetch all the products the there is no need of having show all products API.
**Message - No Product Found or Please add Product ID.**

**Comment by Aqib-Webkul** [comment]
This is not a issue.
If you are requesting url like {{base_url}}/api/v1/products/1 then it is returning the details according to that Product Id.
if requested url is {{base_url}}/api/v1/products/ without any Product Id then it is returning all the available Product details.

**Comment by Amitk-webkul** [comment]
This is not at issue.
