### ISSUE TITLE
Update Product API 

### ISSUE THREAD

**Issue by karan-nukani** [bagisto/rest-api#240]
Hello,
I want to update product details and I follow the swagger doc and details as below
URL: localhost/deodap/bagisto/public/api/v1/admin/catalog/products/2
METHOD: POST
![image](https://github.com/bagisto/rest-api/assets/91069137/8d200b67-62c1-4a51-991e-473ddb62ca1d)

i also tried with PUT method but not working...

**Comment by devansh-webkul** [comment]
It's a little confusing here. For Laravel to detect the PUT request you can send one more param like this, _method: PUT. From Postman when you send a direct PUT request it won't detect it from the Laravel end so for this you need to send a POST with _method: PUT when using form data.
