### ISSUE TITLE
Show Attribute with ID -> It should not respond without Attribute ID.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#25]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we check the Show Attribute with Attribute ID, there we can see that the Attribute details are visible, but when we check the Details without the Attribute without the Attribute id, we are able to see all the Attributes.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Catalog -> Products - > Show Attribute by ID.
**2.** Here in URL, do not use the Attribute id, and then we can fetch all the Attribute details.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/205843179-1a2d433b-0a98-4431-94b2-a9c6150c8c97.mp4

**Expected Result**
Here only attribute with Attribute Id should else a message should appear. If we are able to fetch all the Attribute the there is no need of having show all Attribute API.
**Message - No Attribute Found or Please add Attribute ID.**

**Comment by Aqib-Webkul** [comment]
This is not a issue.
If you are requesting url like {{base_url}}/api/v1/attributes/27 then it is returning the details according to attributes Id.
if requested url is {{base_url}}/api/v1/attributes without any Id then it is returning all the attributes details.

**Comment by ashishkumar-webkul** [comment]
@Aqib-Webkul Sir, as i have checked the concern and understood the working of the URL and also as i have checked the same, it is working fine and hence I am closing the concern. when we hit the URL without the ID then all the data related to the Attibute is appearing.
For Reference please check the video for the same.

**Video**

https://user-images.githubusercontent.com/92721837/230053822-00df082b-3283-4724-a6e4-695227dfcbb0.mp4
