### ISSUE TITLE
cant access the documentation for the api

### ISSUE THREAD

**Issue by AHMED-GAMAL-AG** [bagisto/rest-api#256]
cant access `http://localhost/public/api/shop/documentation
` or `http://localhost/public/api/admin/documentation 
` 

i get  404  when accessing `http://bagisto.test/public/api/admin/documentation`

![image](https://github.com/bagisto/rest-api/assets/76778937/3e8aae7c-d985-4dbf-b69c-c5aa49ae1362)

when i remove the public from the url i get an empty page 

![image](https://github.com/bagisto/rest-api/assets/76778937/e04a5108-d6f3-4a96-a730-3a471462ab9a)

i have set in the .env `SANCTUM_STATEFUL_DOMAINS=http://bagisto.test/public
`

**Comment by shivendra-webkul** [comment]
Hi @AHMED-GAMAL-AG, Thank you for your response. I appreciate your cooperation. I've checked, but the issue isn't appearing on my end either.  Regarding the generation of Swagger documentation, please run the command "php artisan bagisto-rest-api:install". This will allow you to generate the Swagger documentation. After running the command, you can access the Swagger documentation using the following path: [APP_URL]/api/shop/documentation. If you have any further questions or need assistance, feel free to ask. Thank you!
