### ISSUE TITLE
when not sign in api for front page have 500 error 

### ISSUE THREAD

**Issue by imanbahmani** [bagisto/rest-api#257]
when not sign in api for front page have 500 error  and when login its work!

my api list:
http://127.0.0.1/api/products?new=1&sort=created_at-desc&limit=24
http://127.0.0.1/api/products?sort=created_at-desc&limit=12

**Comment by imanbahmani** [comment]
my bagitso version is: 2.1.2

**Comment by shivendra-webkul** [comment]
Hi @imanbahmani, Thank you for your response. I appreciate your cooperation.I have checked API you are using is not compatible with this version. Rest assured, we are currently working on releasing an API version 2.1.2 that is compatible with Bagisto version 2.1.2 We aim to have it available soon. If you have any further questions or need assistance, feel free to ask. Thank you for your patience.

**Comment by amit-webkul** [comment]
I have checked and found this is working fine. Before customer login, I hit the product route to get all the products, and it will work fine. Please check the attached image for reference. 

![products-for-guest](https://github.com/bagisto/rest-api/assets/121479029/bd6b1f1f-a9c6-4c81-9cf7-fe851a79e00b)
