### ISSUE TITLE
Show Attribute Family with ID -> It should not respond without Attribute Family ID.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#26]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we check the Show Attribute Family with Attribute Family ID, there we can see that the Attribute Family details are visible, but when we check the Details without the Attribute Family without the Attribute Family id, we are able to see all the Attribute Family.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Catalog -> Products - > Show Attribute Family by ID.
**2.** Here in URL, do not use the Attribute Family ID, and then we can fetch all the Attribute Family details.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/205846151-0c22a5f4-744a-4e79-8a9a-9ec059877289.mp4

**Expected Result**
Here only attribute family with Attribute Family ID should else a message should appear. If we are able to fetch all the Attribute the there is no need of having show all Attribute Family API

**Comment by Aqib-Webkul** [comment]
This is not a issue.
If you are requesting url like {{base_url}}/api/v1/attribute-families/1 then it is returning the details according to Family Id.
if requested url is {{base_url}}/api/v1/attribute-families without any Id then it is returning all the available details.

**Comment by ashishkumar-webkul** [comment]
@Aqib-Webkul Sir as I have checked and understood the concern related to the working of the URL and found that this is an invalid issue. Hence I am closing the issue. Please consider the video for the reference.

**Video**


https://user-images.githubusercontent.com/92721837/230048061-562bb040-415d-4cfc-b8e6-9375e1312999.mp4
