### ISSUE TITLE
Add password validation when create or update new user.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#262]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Users -> /api/v1/admin/settings/users Store the user

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/47bc9ede-9df8-4287-8fca-d633d1781e3c)

Admin -> Users -> /api/v1/admin/settings/users/{id} Update user

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/8e8380eb-f1cc-4b95-8f73-0489accb9153)

**Admin Screenshot-**

![Screenshot from 2024-05-30 12-50-05](https://github.com/bagisto/rest-api/assets/113347734/5a98ed9e-b891-4f2a-b954-bbdbe7a490e3)

**Comment by mukulsharma-webkul** [comment]
not working, able to create the user by entering 5 chars from API, please take the reference from the video below.

**Video -**

https://github.com/bagisto/rest-api/assets/126852181/c3fabf61-1257-4da0-8ec6-152add811c75
