### ISSUE TITLE
If type "text" is selected then number validation is not adding while creating attribute.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#263]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Attributes -> /api/v1/admin/catalog/attributes Store the attribute

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/f7cce793-ed18-45e5-929b-2460fce202c5

**Comment by mukulsharma-webkul** [comment]
fixed, validation is working on the API.

**Screenshot -**

![Screenshot from 2024-07-01 12-16-19](https://github.com/bagisto/rest-api/assets/126852181/f8229275-885b-4929-9f14-766da1e911a8)
