### ISSUE TITLE
Getting mail in both options for customer notified field.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#264]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Orders -> /api/v1/admin/sales/orders/{id}/comments Store the comment for order

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/8e3f99c9-164c-49d4-a9d2-a1b80a302197)

**Mail Screenshot:**

![Screenshot from 2024-05-30 18-56-57](https://github.com/bagisto/rest-api/assets/113347734/4c0f593b-91ab-4c60-aeba-0c58ee4f5282)

**Comment by mukulsharma-webkul** [comment]
fixed, now getting mail for the customer notified field.

**Screenshot -**
![Screenshot from 2024-07-01 12-58-15](https://github.com/bagisto/rest-api/assets/126852181/584e25b4-17c9-4176-8f49-d1bd142bda45)
