### ISSUE TITLE
Getting email_sent = null in response when generate new invoice.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#265]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Invoices -> /api/v1/admin/sales/invoices/{order_id} Create invoice for an order

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/45685d8c-37e9-4847-a8fe-a59e38bdca3d)

**Mail Screenshot-**

![Screenshot from 2024-05-31 11-18-12](https://github.com/bagisto/rest-api/assets/113347734/497ceff8-c018-4d80-9cbf-6e837a01cf17)

**Comment by mukulsharma-webkul** [comment]
fixed, Email_send = true,

**Screenshot -**

![Screenshot from 2024-07-01 13-22-28](https://github.com/bagisto/rest-api/assets/126852181/a626b971-8ba0-4063-b03c-6d2ca9260372)
