### ISSUE TITLE
Getting email_sent = null in response and receive 3 times shipment email when generate new shipment.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#266]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Shipment -> /api/v1/admin/sales/shipments/{order_id} Create shipment for an order

**Expected Result-**

email_sent = true in response

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/f689ea6d-b88a-4795-92fd-2d276603c83f)

**Mail Screenshot-**

![Screenshot from 2024-05-31 11-32-23](https://github.com/bagisto/rest-api/assets/113347734/eafd23ab-dc45-4b30-8c94-dfedacbf490f)

**Comment by mukulsharma-webkul** [comment]
not working, after hitting /api/v1/admin/sales/shipments/{order_id}  shipment created is showing in API but shipment not showing in admin panel of that Order Id, not email gets after hit the API.

**Please take the reference from the video below -**


https://github.com/bagisto/rest-api/assets/126852181/e644a917-eea0-4c39-a670-693a8e77ee72

**Comment by mukulsharma-webkul** [comment]
verified, create shipment API is working fine.

![Screenshot from 2024-07-04 16-20-15](https://github.com/bagisto/rest-api/assets/126852181/0fdb0368-ef2c-48fa-b88a-c55f75c5f7ad)
