### ISSUE TITLE
Getting email_sent = null in response and receive 2 times refund email when generate new refund.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#267]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Shipment -> /api/v1/admin/sales/shipments/{order_id} Create shipment for an order

**Expected Result-**

email_sent = true in response

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/afacbeb6-6f40-453c-ad05-6de6d1ec1987)

**Mail Screenshot-**

![Screenshot from 2024-05-31 11-48-52](https://github.com/bagisto/rest-api/assets/113347734/9513fedf-9b04-4dfd-a203-bdb22bd066e2)

**Comment by mukulsharma-webkul** [comment]
not working, refund API is showing successfull but on admin panel no refund show, not gets email. 

**Please take the reference from the screenshot/video below -**


https://github.com/bagisto/rest-api/assets/126852181/c4d6b92e-cc1d-4e78-b5c2-4c59d45a23e0

**Comment by mukulsharma-webkul** [comment]
verified, Refund API is working fine.

![Screenshot from 2024-07-04 16-27-47](https://github.com/bagisto/rest-api/assets/126852181/0d91b613-86a6-4701-b4d9-057385e2943c)
