### ISSUE TITLE
Add decimal option for currency create or update api in the request body.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#268]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Currencies -> /api/v1/admin/settings/currencies Store the currency

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/eed2ec52-38f4-4492-924a-9cde7b5cf00e)

Admin -> Currencies -> /api/v1/admin/settings/currencies/{id} Update currency

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation (1)](https://github.com/bagisto/rest-api/assets/113347734/a52f4c93-17f6-406f-951d-7be47508e321)

**Admin Screenshot-**

![Screenshot from 2024-05-31 12-40-52](https://github.com/bagisto/rest-api/assets/113347734/b76ee693-105b-4e21-a3c1-ec3fd1020fe3)

**Comment by mukulsharma-webkul** [comment]
not working, decimal option not showing.

**Screenshot -**

![Screenshot from 2024-07-01 14-50-08](https://github.com/bagisto/rest-api/assets/126852181/304fffba-2bf6-4bd9-af59-8bd508768f23)
