### ISSUE TITLE
Getting 2 as decimal value when admin create new currency.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#269]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Currencies -> /api/v1/admin/settings/currencies Store currency

**Expected Result-**

Decimal value  = 2

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/7efa821c-ba65-4787-8ef1-2e303ccf76cb

**Comment by mukulsharma-webkul** [comment]
not working, showing 2 as a decimal value when admin creates new currency.

**Screenshot -**

![Screenshot from 2024-07-01 15-04-22](https://github.com/bagisto/rest-api/assets/126852181/e4b6ffba-425a-4d75-a8a0-e3b6e62805aa)

**Comment by mukulsharma-webkul** [comment]
verify, now not getting by default 2 as decimal value when admin creates new currency.

![Screenshot from 2024-07-04 10-00-18](https://github.com/bagisto/rest-api/assets/126852181/70589e76-8038-4f23-ace2-474d050769ea)
