### ISSUE TITLE
Getting "Internal server error" if trying to delete the CMS page with invalid id.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#270]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> CMS-pages -> /api/v1/admin/cms/{id} Delete CMS page

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/f15a7748-efa4-4600-9d53-a4466b87e96d)

**Comment by mukulsharma-webkul** [comment]
fixed, now not getting internal server error on invalid CMS id.

**Screenshot -**

![Screenshot from 2024-07-01 15-12-04](https://github.com/bagisto/rest-api/assets/126852181/39172e8e-0975-4506-99fe-351f7e887da1)
