### ISSUE TITLE
Getting "Internal Server Error" when try to store exchange rate with invalid target currency.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#271]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Exchange Rates -> /api/v1/admin/settings/exchange-rates Store the exchnage rate

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/aee5dc86-766f-41d3-87b5-1dd2f2650f51)

**Comment by amit-webkul** [comment]
As per your concern, I have created a new PR where I have handled all types of exceptions. You can visit my [PR] (https://github.com/bagisto/rest-api/pull/323).

**Comment by mukulsharma-webkul** [comment]
fixed, now not getting Internal Server Error on invalid target currency.

**Screenshot -**

![Screenshot from 2024-07-01 15-19-36](https://github.com/bagisto/rest-api/assets/126852181/629ecc95-2dd3-40dc-a437-f823cb90bc3c)
