### ISSUE TITLE
Not getting updated response after update the CMS page.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#272]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Cms-pages -> /api/v1/admin/cms/{id} Update the CMS page

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/38e6c0aa-8ae3-4e4e-8836-e448183adeb8

**Comment by mukulsharma-webkul** [comment]
fixed, the response is shown updated after updating the CMS page.

**Video -**


https://github.com/bagisto/rest-api/assets/126852181/fe7a0796-69aa-4759-ac1d-4fe75c5e6c4b
