### ISSUE TITLE
Getting "Internal server error" and mention 2 times category id parameter while getting product list form the shop.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#273]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Products -> /api/v1/products Get product list for the shop

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/d0ab97a4-2f24-40ca-9a66-1270c36dcf7b

**Comment by mukulsharma-webkul** [comment]
now not getting internal server error but showing 2 times category id parameters.

**Please take the reference from the video below -**


https://github.com/bagisto/rest-api/assets/126852181/6c4602e9-810a-4122-a762-06b70ebd6cfa

**Comment by mukulsharma-webkul** [comment]
verify, Products -> /api/v1/products Get product list for the shop API working fine now.

![Screenshot from 2024-07-04 10-06-28](https://github.com/bagisto/rest-api/assets/126852181/8a777aee-9ed1-4f9b-9081-a917ad1b5fa2)
![Screenshot from 2024-07-04 10-07-17](https://github.com/bagisto/rest-api/assets/126852181/bf85287b-194d-4aed-8959-933c65b32877)
