### ISSUE TITLE
Getting "Internal Server Error" when get configurable product options by id for the configurable product.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#275]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Products -> /api/v1/products/{id}/configurable-config Get configurable product options by id

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/1f2f5e0e-d310-4e0e-a658-80c658df15b9

**Comment by amit-webkul** [comment]
I have checked and found that the issue is not appearing. Please check the attached screen shot:

![shop-product-config](https://github.com/bagisto/rest-api/assets/121479029/c1fbbc7c-30c5-4f84-a6f5-3b00ce62fb7a)

**Comment by mukulsharma-webkul** [comment]
verifed, able to get the config product variant details by id.

**Video -**

https://github.com/bagisto/rest-api/assets/126852181/43717d8e-324c-49c5-846e-9ae3dc4abcfd
