### ISSUE TITLE
Need to add validation if customer try to login with less than 6 character.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#276]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Customers -> /api/v1/customer/login Login Customer

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/77d44a5a-d4a2-4490-bc6a-2c6e919e29de)

**Comment by amit-webkul** [comment]
Here I have checked an d found that, 

This is not an issue because we have already responded to invalid credentials for customer login, so there is no need to add pass limitation validation.

**Comment by mukulsharma-webkul** [comment]
verified, here it is responded on invalid credentials while login, so here no need to add the password limitation validation.

**Screenshot -**

![Screenshot from 2024-07-01 16-24-45](https://github.com/bagisto/rest-api/assets/126852181/2ab1a7b1-dd9d-4325-a217-f97bfef26201)
