### ISSUE TITLE
Getting "Internal server error" when customer give review to the product.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#277]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Products -> /api/v1/products/{product_id}/reviews Store products's review by login customer

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/ae5f3138-9bbc-45fe-923e-5225247b7347

**Comment by amit-webkul** [comment]
I have checked and verified that this issue does not appear with Bagisto v2.1.2.

Kindly check the attached image and video for reference.

Link : [Image](https://prnt.sc/IutRXDZMc3F0), [video](https://webkul.chatwhizz.com/share/view-recording/66754fbf2091350726ed9fa5)

**Comment by mukulsharma-webkul** [comment]
unable to give a review of the product.



[Video -](https://webkul.chatwhizz.com/share/view-recording/66828e152091350726fe1f6c)

**Comment by amit-webkul** [comment]
@mukulsharma-webkul ,

Kindly check again after the user logged in. I have checked your attached video, and your user is not logged in, so you are facing an error.

**Comment by mukulsharma-webkul** [comment]
verify, able to gave a review to the product.

![Screenshot from 2024-07-04 13-59-49](https://github.com/bagisto/rest-api/assets/126852181/a07733ef-5a6b-41ee-a726-c51076f8cc9d)
