### ISSUE TITLE
Store and Admin|| Need email, postcode and phone number validation while adding new address.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#278]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Addresses -> /api/v1/customer/addresses Create customer's address

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/7cb6aa6d-8253-4093-8fe1-3912574cc419

**API-**

Store -> Addresses -> /api/v1/customer/addresses/{id} Update customer's address

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/e0b2f75b-f692-47a9-995e-d9957a6add95)

Admin -> Customer Addresses -> /api/v1/admin/customers/{customer_id}/addresses Store the customer's address

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/f0a025a8-e581-4070-ad59-3797bac1ea19)

Admin -> Customer Addresses -> /api/v1/admin/customers/{customer_id}/addresses/{id} Update customer's addresses

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/15758764-f1eb-45be-be1e-98661b16a1ca)

**Comment by mukulsharma-webkul** [comment]
fixed, validation is working fine on the phone no, email, and postcode.

![Screenshot from 2024-07-05 13-05-50](https://github.com/bagisto/rest-api/assets/126852181/fed4a803-63b8-43b7-b303-9c7a7fd90308)
