### ISSUE TITLE
Need to improve the response message when order is cancelled by customer.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#279]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Orders -> /api/v1/customer/orders/{id}/cancel Cancel customer order's by id

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/f4a0264f-ef26-49c3-b09a-bef0d4c96bc0)

**Comment by mukulsharma-webkul** [comment]
verified, order canceled message updated.

![Screenshot from 2024-07-01 18-14-24](https://github.com/bagisto/rest-api/assets/126852181/4f174f37-7602-410c-98e1-d336e81d8ead)
