### ISSUE TITLE
Getting "Internal Server Error" on hit get customer wishlist api.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#280]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Wishlists -> /api/v1/customer/wishlist Get Customer's wishlist

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/bdb3d433-8a8b-4bfd-9056-e92b058a5152)

**Comment by amit-webkul** [comment]
I have checked and found the issue in not appearing in Bagisto with the v2.1.2 version branch.
I have taken a screenshot. Please take a look for a reference:

![REST-API](https://github.com/bagisto/rest-api/assets/121479029/55bb5c74-d5c8-4a35-8800-20da4a895162)

**Comment by mukulsharma-webkul** [comment]
verified, the wishlist API working fine.
