### ISSUE TITLE
Getting "Internal Server Error" when hit Add or Remove product to customer's wishlist api.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#281]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Wishlists -> /api/v1/customer/wishlist/{id} Add or Remove product to customer's wishlist

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/2dd50497-1766-452a-bc4f-0233e408b877)

**Comment by amit-webkul** [comment]
I have checked and found when i was add or remove the product in wishlist, It was working fine and there are not any issue.
Please see the screenshots for references.

Product added to the wishlist:
![REST-API-Wishlist](https://github.com/bagisto/rest-api/assets/121479029/9d33088c-6e7f-4575-90a1-e28d44edb2b8)

Product remove from wishlist:
![REST-API-Wishlist-remove](https://github.com/bagisto/rest-api/assets/121479029/ec5a8b39-6d90-44be-bc97-33e57f4271bf)

**Comment by mukulsharma-webkul** [comment]
verified.

![Screenshot from 2024-07-01 18-52-04](https://github.com/bagisto/rest-api/assets/126852181/bb62d13c-32a7-4b40-bc17-95ccd7c2301b)
