### ISSUE TITLE
Getting "Internal Server Error" on hit Move product from wishlist to cart api.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#282]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Wishlists -> /api/v1/customer/wishlist/{id}/move-to-cart Move product from wishlist to cart

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/1f4a81e1-bb26-43ba-a70d-5dca2dfe76d4)

**Comment by amit-webkul** [comment]
I have checked, and this is working fine. Also, I have attached a screenshot for reference:

![Rest-APi-move-to--cart](https://github.com/bagisto/rest-api/assets/121479029/0e6db213-b889-44f7-8053-3fcc3bd67683)

**Comment by mukulsharma-webkul** [comment]
verified, Item is moved from wishlist to cart by API.

![Screenshot from 2024-07-01 18-56-45](https://github.com/bagisto/rest-api/assets/126852181/1c0943f7-5dc4-44fd-862b-5db0c59ef693)
