### ISSUE TITLE
Getting  "Internal Server Error" on hit Add product to customer's cart api.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#283]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Cart -> /api/v1/customer/cart/add/{productId} Add product to customer's cart

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/f5a34cbf-1b72-49e7-8e42-4c6c76c54c6c

**Comment by amit-webkul** [comment]
I have checked and found that the add-to-cart product is working fine. Please find a screenshot for reference:

![Rest-Api-add-to-cart](https://github.com/bagisto/rest-api/assets/121479029/41006426-1d65-429c-a06b-3fd3e2132864)

**Comment by mukulsharma-webkul** [comment]
verified, add to cart API working fine.

![Screenshot from 2024-07-01 19-03-34](https://github.com/bagisto/rest-api/assets/126852181/01335f0e-2aac-43ce-93ed-c20011f99554)
