### ISSUE TITLE
Getting "Internal Server Error" in cart page apis.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#284]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Cart -> /api/v1/customer/cart Get customer/guest's cart

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/3edf8b6c-4649-46ec-8ed0-e315bf0084d9)

Store -> Cart -> /api/v1/customer/cart/add/{productId} Add product to customer's cart

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/b46894ad-e2fb-47ec-be88-e31bea4ea05f)

Store -> Cart -> /api/v1/customer/cart/update Update cart item

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/be9e83c1-b4b4-49cf-875e-3b1d5997cd14)

Store -> Cart -> /api/v1/customer/cart/remove/{cartItemId} Delete item from cart using cart item id

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/16a8105c-ffce-4786-b7cc-42711411413b)

Store -> Cart -> /api/v1/customer/cart/coupon Apply coupon to cart

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation (1)](https://github.com/bagisto/rest-api/assets/113347734/e485dd1e-c335-48d5-9282-011a8494ded3)

Store -> Cart -> /api/v1/customer/cart/coupon Remove cart coupon

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation (1)](https://github.com/bagisto/rest-api/assets/113347734/d370b0be-1d4d-4654-8983-8e706396416f)

**Comment by amit-webkul** [comment]
I have checked all the APi's one by one and found that all APi's are working fine. I have added a screenshot for all APi's as a reference:

Cart page:
![Rest-APi-cart-page](https://github.com/bagisto/rest-api/assets/121479029/e8d90fb4-3386-4504-9e84-3bde17ba0ffb)

Cart Move to Wishlist:
![Rest-APi-Cart-page-move-to-wishlist](https://github.com/bagisto/rest-api/assets/121479029/66641730-9fd1-492d-b2db-ef01ffc3a097)

Remove from cart:
![REST-API-cart-remove](https://github.com/bagisto/rest-api/assets/121479029/b67eb8c1-6d26-4c01-8f74-c9657b5c1a5f)

Update cart quantity:
![REST-API-Cart-update-qty](https://github.com/bagisto/rest-api/assets/121479029/06b1974e-896e-4b0d-8ce6-7746813970ff)

Apply the coupon code in the cart:
![REST-API-Coupon](https://github.com/bagisto/rest-api/assets/121479029/3c45dd61-f513-4ae7-859d-2f308207ff16)

Remove the coupon from the cart. 
![REST-API-Coupon-remove](https://github.com/bagisto/rest-api/assets/121479029/018e49f6-8ccb-497e-bce4-358217daa89b)
