### ISSUE TITLE
Getting "Internal Server Error" in checkout apis.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#285]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Store -> Checkout -> /api/v1/customer/checkout/save-address Save addresses at the checkout

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/3852aea7-d41d-414c-a717-d39981cf432d)

Store -> Checkout -> /api/v1/customer/checkout/save-shipping Save shipping method at the checkout

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/4e9458b2-a304-4e6b-8ebe-75af8db1fbe3)

Store -> Checkout -> /api/v1/customer/checkout/save-payment Save payment method at the checkout

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation (1)](https://github.com/bagisto/rest-api/assets/113347734/4b7ee263-519f-405b-b459-5a0c58751a9b)

Store -> Checkout -> /api/v1/customer/checkout/check-minimum-order Check minimun order at the checkout

**Reference Screenshot-**

![Bagisto-Rest-Shop-API-Documentation (1)](https://github.com/bagisto/rest-api/assets/113347734/9568cf79-6cb8-4cb5-831c-73c12bb63835)

**Comment by amit-webkul** [comment]
I have checked and found that all the APi's mentioned above are working fine. Also, I have attached screenshots for reference:

Minimum Order in Cart API:
![REst-api-checkout-minimum-cart-order](https://github.com/bagisto/rest-api/assets/121479029/4f382ffb-fb39-4149-baf2-002cab4be990)

Save ADDRESS API:
![Rest-api-checkout-save-addres](https://github.com/bagisto/rest-api/assets/121479029/cb774290-a3ad-46b5-bc9a-49b9cfa6bcd3)

Save Payment Method API:
![Rest-api-checkout-save-payment-method](https://github.com/bagisto/rest-api/assets/121479029/a5226598-433a-4741-9f27-8a1b9292e13a)

Save Shipping Method API:
![rest-api-checkout-save-shipping](https://github.com/bagisto/rest-api/assets/121479029/b839c9c2-0e97-4260-880e-c0b79cbeeef7)
