### ISSUE TITLE
Getting "Internal Server Error" if admin trying to mass delete the unavilable reviews.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#286]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Customer Reviews -> /api/v1/admin/customers/reviews/mass-destroy Mass delete customer review by id

**Expected Result-**

Response Code: 404 Not Found

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/d0fad053-76ec-48e8-9881-9de52fae22a8)

**Comment by amit-webkul** [comment]
I have checked and found the Mass Delete in the Customer Review section is working fine. I have attached a screenshot for reference:

![reST-API-CUSTOMER-REVIEW-MASS-DESTROY](https://github.com/bagisto/rest-api/assets/121479029/b003aa69-b441-4b6b-a457-50299e92cc29)

**Comment by mukulsharma-webkul** [comment]
verify, mass delete review API working fine.

![Screenshot from 2024-07-04 12-17-14](https://github.com/bagisto/rest-api/assets/126852181/748b5eeb-5872-40a6-a4a2-75927334bd55)
