### ISSUE TITLE
Getting "Internal Server Error" when update catalog price rule.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#288]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Catalog Rules -> /api/v1/admin/promotions/catalog-rules/{id} Update catalog rule

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/1b50be86-c9d2-4954-9b42-daa81755ae7a)

**Comment by mukulsharma-webkul** [comment]
not working, getting an internal server error.

**Video -**


https://github.com/bagisto/rest-api/assets/126852181/22b143f7-97a5-4b5a-be55-2edf17213e95

**Comment by mukulsharma-webkul** [comment]
verify, Catalog Rule is working and updated.

![Screenshot from 2024-07-04 17-28-14](https://github.com/bagisto/rest-api/assets/126852181/4b5eca0f-2102-4ac4-ad20-e14d8896023b)
