### ISSUE TITLE
Getting "Internal Server Error" when update cart price rule.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#289]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Cart Rules -> /api/v1/admin/promotions/cart-rules/{id} Update cart rule

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/ea22f951-dd20-4af3-b49a-13da2d6f947d)

**Comment by amit-webkul** [comment]
I have checked the Cart Rule update, and it is working fine. Also, I have attached a screenshot for reference.

![REst-api-cart-rule-update](https://github.com/bagisto/rest-api/assets/121479029/5bc56d00-c0ec-4941-96ab-d5764416a42c)

**Comment by mukulsharma-webkul** [comment]
not working properly, here cart rule is updated on the admin panel but showing an Internal server error on API.

**Video -**


https://github.com/bagisto/rest-api/assets/126852181/b2251d10-22b8-43b3-b354-b35472378c7c

**Comment by mukulsharma-webkul** [comment]
verified, Cart Rule is working fine.

![Screenshot from 2024-07-04 16-54-17](https://github.com/bagisto/rest-api/assets/126852181/99ee03d8-ecc5-4d7d-9315-c3f86aafb86b)
