### ISSUE TITLE
There should be an API for customer for Forgot Password Recovery.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#29]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we check the Customer API, there we can see Login, Logout and Register API, but there should be an API where a customer can have the option of Forgot Password API.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customer -> Authentication

**Expected Result**
Here we should have an API for the Customer Forgot Password, for recovery of the password.

**Comment by amit-webkul** [comment]
@Amitk-webkul , I have added Endpoint for forgot password. Please check .

**Comment by Amitk-webkul** [comment]
Checked and verified now it is working fine. [Here](https://prnt.sc/9YHm7J9BWVJz)
