### ISSUE TITLE
Getting response code 200 for the unavailable newsletter subsciption for the update subscriber api. 

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#290]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Newsletter Subscriptions -> /api/v1/admin/marketing/communications/subscribers/{id} Update Subscriber

**Expected Result-**

Response Code - 404 Not Found

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/36c3b4c3-6c33-4d57-9332-b5e4ec336939

**Comment by amit-webkul** [comment]
I have checked and verified that this is not an issue and is working fine. I have also attached a screenshot for reference:

![rest-api-subscriber-list-update](https://github.com/bagisto/rest-api/assets/121479029/2999efe8-3b7e-4b0f-b225-c933562bb308)

**Comment by mukulsharma-webkul** [comment]
verified, updated newsletter subscriber API is working fine.

**Screenshot -**

![Screenshot from 2024-07-03 10-13-05](https://github.com/bagisto/rest-api/assets/126852181/f01379ca-f988-42ba-b9d2-44f8216ea830)
