### ISSUE TITLE
Getting "Internal Server Error" when update the sitemap.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#291]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Sitemaps -> /api/v1/admin/marketing/search-seo/sitemaps/{id} Update Sitemaps

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/10551a37-83ee-4807-9930-1b547af05e5e)

**Comment by amit-webkul** [comment]
I have checked and found that the update sitemap is working fine. Please find attached a reference: 

![Rest-APi-Sitemap](https://github.com/bagisto/rest-api/assets/121479029/21be1803-b52f-4a8b-98c5-d80b984d6658)

**Comment by mukulsharma-webkul** [comment]
sitemap is updated but getting internal server error on the API, please take the reference from the video https://jam.dev/c/a8b79957-1797-4605-8eb8-299edce022c5

**Comment by mukulsharma-webkul** [comment]
verified, Sitemap is created and updated.

![Screenshot from 2024-07-05 17-43-47](https://github.com/bagisto/rest-api/assets/126852181/eeb6e0fc-0f92-4f32-8716-41758c14c97b)
