### ISSUE TITLE
Getting "Internal Server Error" when update the theme.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#292]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Themes  -> /api/v1/admin/settings/theme/customizations/{id} Update Theme

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/b8cbce22-367a-4d50-af46-642a7df1552d)

**Comment by amit-webkul** [comment]
I have checked, and there are not any issues. I have added a screenshot for reference and also updated some changes in Swager for related APIs.

![theme-update](https://github.com/bagisto/rest-api/assets/121479029/7c92543b-238e-4faf-93e0-c06c77a83344)

**Comment by mukulsharma-webkul** [comment]
checking and found that the theme is updated on admin panel but getting internal server error in the API, please take the reference from the video below. 
https://jam.dev/c/2640936e-e3b3-4f6e-b28d-957dc3c28bd7

**Comment by mukulsharma-webkul** [comment]
verify, the theme update API working fine.

![Screenshot from 2024-07-04 15-40-55](https://github.com/bagisto/rest-api/assets/126852181/4348f2b7-9cdf-4186-a7b1-bd79b3bdb171)
