### ISSUE TITLE
Getting "Internal Server Error" when delete unavailable theme.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#293]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Themes -> /api/v1/admin/settings/theme/customizations/{id} Delete Theme options by id

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/fe6068b0-0626-4d19-adf5-dab3ac670548)

**Comment by mukulsharma-webkul** [comment]
verified, delete theme API working fine.

![Screenshot from 2024-07-03 11-15-48](https://github.com/bagisto/rest-api/assets/126852181/a2ea32aa-ed74-4bac-b2fe-83aef0102e38)
