### ISSUE TITLE
New store theme is not visible at the admin end.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#294]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Themes -> /api/v1/admin/settings/theme/customizations Store the theme

**Reference Screenshot-**

https://github.com/bagisto/rest-api/assets/113347734/10d0f59c-7cbb-40f9-bbf5-80474a396141

**Comment by amit-webkul** [comment]
I have checked, This is not an issue, Actually, this is working fine with our flow. After theme creation, we need to update that theme for status and more sections. After that, this theme will be available in the theme data grid.

You can also check the same concern on the web; they are also doing the same thing.

**Comment by mukulsharma-webkul** [comment]
verifed, as per discuss with @amit-webkul , theme is create but not visible in datagrid due to by default OFF status and no added its additional details.

![Screenshot from 2024-07-04 13-21-13](https://github.com/bagisto/rest-api/assets/126852181/c59ace2d-0dc1-43fa-b46d-ed734c4e533f)
