### ISSUE TITLE
Need email validation while store or update new customer.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#295]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Customers -> /api/v1/admin/customers Store the customer

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/b72c195f-1f56-432e-96d0-2bab3369aaa5)

Admin -> Customers -> /api/v1/admin/customers/{id} Update Customer

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/0283ba40-0ba8-4909-abd7-8fd5075747de)

**Admin Screenshot-**

![Screenshot from 2024-06-04 14-51-28](https://github.com/bagisto/rest-api/assets/113347734/d796e1de-16f4-4480-b322-4c1e6019a7ae)

**Comment by mukulsharma-webkul** [comment]
verified, email validation is working fine while creating the customer.
