### ISSUE TITLE
Not receiving the email by customer notify api.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#296]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Customers -> /api/v1/admin/customers/{id}/notes Store the customer's note by customer id

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/83ba6bad-b151-40c2-8b5f-074876d0ed8e)

**Email Screenshot-**

![Mailtrap-Email-Delivery-Platform](https://github.com/bagisto/rest-api/assets/113347734/2fa706a2-a6c2-4522-ba36-8e040615266c)

**Comment by mukulsharma-webkul** [comment]
verified, mail functionality is working fine.

![Screenshot from 2024-07-03 12-19-22](https://github.com/bagisto/rest-api/assets/126852181/a2880d55-7457-48d6-979c-3d24694669b7)
