### ISSUE TITLE
Not getting correct warning message in response if update inventory source with invalid phone number.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#297]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Inventory Sources -> /api/v1/admin/settings/inventory-sources/{id} Update inventory source

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/621b2824-9ad6-4c5e-a366-05c5e9fb3cd6)

**Comment by mukulsharma-webkul** [comment]
verified, the message is showing fine on the given invalid phone number.

![Screenshot from 2024-07-04 16-08-36](https://github.com/bagisto/rest-api/assets/126852181/a18abcd9-d64c-454d-9c89-77d8eb131d3b)
