### ISSUE TITLE
Getting exception from admin end when admin edit the newly store channel by api.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#298]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Channels -> /api/v1/admin/settings/channels Store the channel

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/3e7815f9-80fa-4c15-a2f2-3935d55f11c4

**Comment by mukulsharma-webkul** [comment]
verified, channel created, and edited successfully.

https://jam.dev/c/177fd64b-c3bf-46a7-8e9a-d74099580598
