### ISSUE TITLE
Getting error when trying to update the channel.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#299]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Channels -> /api/v1/admin/settings/channels/{id} Update channel

**Reference Video-**

https://github.com/bagisto/rest-api/assets/113347734/f1937134-9b4a-4d98-a1a9-b20ba42e674a

**Comment by mukulsharma-webkul** [comment]
verified, working fine.

https://jam.dev/c/1f9441cb-5b0a-4b59-bc41-5fb84866c80f
