### ISSUE TITLE
In Create Transaction API - Shipping Repository Details are missing.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#30]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we are checking the details of the transaction and when we try to create a new transaction with the API, shipping repository details are missing, hence we are unable to create a transaction.

**Steps to Reproduce**
**1.** Go to Postman -> Bagisto -> Admin -> Sales -> Transactions ->  Create Transactions
**2.** When we fill the form data and then check the details we get the error.

**Expected Result**
Shipping Repository need to be added in the Create Transaction API.

**Comment by Aqib-Webkul** [comment]
Need more details, as I have checked and not getting the issue

**Comment by Amitk-webkul** [comment]
This is working fine.
