### ISSUE TITLE
Getting "Internal Server Error" when update simple and virtual products.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#301]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Products -> /api/v1/admin/catalog/products/{id} Update product (Simple, Virtual)

**Simple Product Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/066820b5-c269-4572-8a22-724fa875afd1)

**Virtual Product Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/fef0ed66-e98a-48e5-8ec6-224f3167524f)

**Comment by amit-webkul** [comment]
For reference, I have added an image Where you can check the entries which you need to add on your product update. you can update as per your requirements (Like: up-sell product ID, cross-sell product ID, related-sell product ID, etc...) 

![product-creation](https://github.com/bagisto/rest-api/assets/121479029/f5759537-36fa-46e1-a7ab-ab8a2421993b)

**Comment by mukulsharma-webkul** [comment]
verify, able to update simple and virtual products.

![Screenshot from 2024-07-04 12-30-30](https://github.com/bagisto/rest-api/assets/126852181/aaef71a7-08d2-41d2-ad27-f26d8acab6b4)
