### ISSUE TITLE
Getting "Internal Server Error" when Update the catalog product's inventory.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#302]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Products -> /api/v1/admin/catalog/products/{id}/inventories Update the catalog product's inventory

**Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/e7688a9e-ecd2-4db9-9149-587e9bc4b2ee)

**Comment by amit-webkul** [comment]
I have checked, and this is working fine. Please check the attached screenshot: 

![product-inventory-update](https://github.com/bagisto/rest-api/assets/121479029/0e0537b6-8a26-4e2e-a2fc-5b99e0c0888c)

**Comment by mukulsharma-webkul** [comment]
working fine,

![Screenshot from 2024-07-03 15-14-47](https://github.com/bagisto/rest-api/assets/126852181/d0bed867-af88-4fd8-af95-e88cd375bd1b)
