### ISSUE TITLE
Get Meta Data - We should be able to get the Meta Data information by API.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#32]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we check the concern related to the meta data, with the help of API we should be able to fetch the information related to the Meta Data.

**Steps to Reproduce**
**1.** Go to Postman -> Bagisto -> Admin -> Velocity -> Meta Data
**2.** Here we should be able to fetch the information related to meta data pages.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Get Meta Data](https://user-images.githubusercontent.com/92721837/206364544-810758c1-57b2-4bb1-916e-6989c79b9a3a.png)

![Screenshot from 2022-12-08 11-01-12](https://user-images.githubusercontent.com/92721837/206364570-1236745a-df72-4a06-971a-58dc9aa56b83.png)

**Expected Result**
Please add the details related to the same, as we are getting issue when we are passing the information.

**Comment by Amitk-webkul** [comment]
It is working fine. [Here](https://tinyurl.com/2m266nf8)
