### ISSUE TITLE
In Mass Update - Header Content, need proper Form Data.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#34]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we want to **update** the content of the **Header** in **mass**, we do not have the proper **Form Data**, if we pass the data with the help of indexes, we are unable to update the header content in mass.

**Steps to Reproduce**
**1.** Go to Postman -> Bagisto -> Admin -> Velocity -> Header Content -> Mass Update Header Content
**2.** Here we need a proper Form Data

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-12-08 13-06-04](https://user-images.githubusercontent.com/92721837/206386761-3189c8de-1712-4d37-a427-f7216205b88f.png)

**Expected Result**
Please add a proper Form Data for the Mass Update of the Header Content.

**Comment by Aqib-Webkul** [comment]
This is not a issue value should passed like this 1,2

**Comment by Amitk-webkul** [comment]
This is working fine. [Here](https://tinyurl.com/2jk3os2z)
