### ISSUE TITLE
Email verification is not sent while registering a new customer through (REST API) /api/v1/customer/register

### ISSUE THREAD

**Issue by archtheonly** [bagisto/rest-api#347]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

from 2.1 to 2.2.2

### Issue Description

Hello!
First of all, thank you for a great product.
I am having this bug from version 2.1, it is still present in 2.2.2 also (just tested yesterday).

The bug is the following;
When the Customer creates a new account (I have Velacity theme), the email verification works pretty good.
But I am also using the REST API for another Vue application.
By sending POST request to /api/v1/customer/register, I get 200 and the account is created, the customer can log in without any issue, but the email verification is not sent.
![image](https://github.com/user-attachments/assets/2539f7ee-21d3-4a88-85ad-eb589867b9f1)
But if I try to send a reset password by (/api/v1/customer/forgot-password), in this case the email is sent successfully.
I tried to figure out that by checking the Velacity theme header requests and found out some token is being generated while sending the request, maybe the problem is associated with that.
Thank you in advance for helping and fixing this!

### Preconditions

I am using php 8.1 and Laravel 10 on ubuntu 22.04

### Steps to reproduce

1. Go to [/api/v1/customer/register](https://domainame.com/api/shop/documentation#/Customers/registerCustomer)
2. Click on try out and send a test request.
3. Scroll down to the code status and check the status
4. See error (by checking the email application)

### Expected Result

The verification email should've been sent!

### Actual Result

The verification email is not sent!

**Comment by archtheonly** [comment]
Hello!
Thank you@amit-webkul for assigning the bug.
Here is the log error, in case you need that.

[previous exception] [object] (Illuminate\\Routing\\Exceptions\\UrlGenerationException(code: 0): Missing required parameter for [Route: shop.customers.verify] [URI: customer/verify-account/{token}] [Missing parameter: token]. >[stacktrace]

**Comment by archtheonly** [comment]
Also wanted to ask @amit-webkul, is there any updates from you?

**Comment by amit-webkul** [comment]
Hello, @archtheonly 

We are working on it and will update you soon.

**Comment by archtheonly** [comment]
Hello!
@amit-webkul Is there any updates?

**Comment by archtheonly** [comment]
@amit-webkul

**Comment by mukulsharma-webkul** [comment]
verified, the email is getting on while registering a new customer through REST API.

**Screenshot -**

![Screenshot from 2024-09-02 15-28-38](https://github.com/user-attachments/assets/10390052-7916-4fa5-bc69-f3d3f8171f3e)
![mail](https://github.com/user-attachments/assets/b10aeafe-a5d9-497c-ab40-2ba5aadaeec5)

**Comment by archtheonly** [comment]
Great, thank you!
