### ISSUE TITLE
Incorrect Date is visible in the Admin End after creating Catalog Rule with API.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#35]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we fill the details of the **Start's From and End Till in API** and hit  the API, after that we can see **200 OK message**. But when we check the same concern at the **Admin end**, there we can see the **issue** in **Start's From and End Till**.

**Steps to Reproduce**
**1.** Go to Postman -> Bagisto -> Admin -> Marketing - > Catalog Rules -> Create Catalog Rule
**2.** Now fill the dates in the API and after that check the Admin End.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-12-08 15-28-28](https://user-images.githubusercontent.com/92721837/206419376-d30403c0-71c4-424c-8894-2402a875b80b.png)

![date stored](https://user-images.githubusercontent.com/92721837/206419398-54824f17-b945-4322-a63f-1a393bcff677.png)

**Expected Result**
The Dates which we have added in the API, should reflect back in the admin end also.

**Comment by ashishkumar-webkul** [comment]
Same issue is appearing for the Cart Rule creating with the API.

**Comment by Aqib-Webkul** [comment]
This is not a issue Date value should be passed like this 2022-12-05

**Comment by Amitk-webkul** [comment]
This is working fine.
