### ISSUE TITLE
On the Admin API -> Categories API -> Get Categories API -> while hitting the API getting an internal server error

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#351]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the Admin API -> Categories API -> Get Categories API -> while hitting the API getting an internal server error.

**Please take the reference from the screenshot below -**

https://jam.dev/c/d66c781a-8a85-4787-bce8-bc59f2c5162d

**Comment by amit-webkul** [comment]
@mukulsharma-webkul 

I have checked and found that the issue is not appearing, and I have also recorded a video for your reference.
[Recorded video](https://webkul.chatwhizz.com/share/view-recording/66d054ba8e63b50c724e3895)

**Comment by mukulsharma-webkul** [comment]
getting exceptions in get category API. Kindly take the reference from the video below.

**Video -**

https://webkul.chatwhizz.com/share/view-recording/66d55fab60b8692d4c3a5826
