### ISSUE TITLE
On the Admin API -> Categories API -> Mass Delete Categories -> while hitting the API getting exception.

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#352]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the Admin API -> Categories API -> Mass Delete Categories -> while hitting the API getting exception.

**Please take the reference from the screneshot below -**

![Screenshot from 2024-08-14 18-25-51](https://github.com/user-attachments/assets/470e74f4-0589-48df-aef7-245f0eda1790)

**Comment by amit-webkul** [comment]
Bug Fixed in this [commit](https://github.com/bagisto/rest-api/pull/330/commits/508dc8965f783964d784fdb50a4ff649cc62993c)

**Comment by mukulsharma-webkul** [comment]
verified, now Mass Delete Categories API working fine.

**Screenshot -**

![Screenshot from 2024-09-02 10-16-50](https://github.com/user-attachments/assets/74ce2f6b-ecd5-40fe-8f02-ec4ff9ade500)
