### ISSUE TITLE
On the admin API -> Store the customer -> getting internal server error on hitting the API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#354]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the admin API -> Store the customer -> getting internal server error on hitting the API.

**Please take the reference from the video below -**

https://jam.dev/c/e5cbbc75-0c29-44a6-bac8-2004e19cc989

**Comment by amit-webkul** [comment]
Bug Fixed In this [commit](https://github.com/bagisto/rest-api/pull/330/commits/4e6a0a2b69b5bace8e6e998942d13ccb028225d3)

**Comment by mukulsharma-webkul** [comment]
verified, Store the Customer API is working fine now, so I am closing the issue.

![Screenshot from 2024-09-02 10-27-50](https://github.com/user-attachments/assets/ecaf8136-633f-4830-906b-18ec3997631b)
