### ISSUE TITLE
On the admin API -> Update customer -> getting internal server error on hitting the API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#355]
Rest API - v2.2.0

Bagisto Core - v2.2.0

Description -

On the admin API -> Update customer -> getting internal server error on hitting the API.

Please take the reference from the video below -

https://jam.dev/c/50fc3017-3536-4bb5-8787-3b2edb5518eb

**Comment by amit-webkul** [comment]
Bug Fixed In this [commit](https://github.com/bagisto/rest-api/pull/330/commits/4e6a0a2b69b5bace8e6e998942d13ccb028225d3)

**Comment by mukulsharma-webkul** [comment]
verified, Update Customer API is working fine now.

**Screenshot -**

![Screenshot from 2024-09-02 10-35-05](https://github.com/user-attachments/assets/ada46730-a58a-474b-b35a-9ec83e04061d)
