### ISSUE TITLE
On the admin API -> CustomerReview API -> Please add the POST API for create customer reviews by id API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#356]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the admin API -> CustomerReview API -> Please add the POST API for create customer reviews by id API.

**Please take the reference from the screenshot below -**

![postapi](https://github.com/user-attachments/assets/6f16a5b5-9e45-49af-bdb2-09ac5e993bd2)

**Comment by ashishkumar-webkul** [comment]
@mukulsharma-webkul 
This issue is invalid as from admin end we do not add  review for customer on product, we only update the status.
