### ISSUE TITLE
While hitting Get admin Customer review API -> on the product detail section -> <p> tag is showing on description and short description in API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#357]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the admin API -> CustomerReview API -> While hitting Get admin Customer review API -> on the product detail section -> <p> tag is showing on description and short description in API.

Note -> this issue is showing all Customer Reviews API.

**Please take the reference from the screenshot below -**

![Screenshot from 2024-08-16 13-32-04](https://github.com/user-attachments/assets/0e5ce4e2-d717-474f-a89b-8a38f2d743ff)

**Comment by amit-webkul** [comment]
While saving the product, the tag is saved with content in the database. There are no issues in the API.
