### ISSUE TITLE
On the admin API -> Sales Reporting API -> getting internal server error

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#358]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the admin API -> Sales Reporting API -> getting internal server error.

**Please take the reference from the video below -**

https://jam.dev/c/35cbd4b4-990f-422d-bdc0-2087827d5836

**Comment by amit-webkul** [comment]
Bug Fixed in this [commit](https://github.com/bagisto/rest-api/pull/330/commits/4e6a0a2b69b5bace8e6e998942d13ccb028225d3)

**Comment by mukulsharma-webkul** [comment]
verified, Sales API working fine,

**Video -**

https://webkul.chatwhizz.com/share/view-recording/66d5543e60b8692d4c3a27c6
