### ISSUE TITLE
In Mass Update -> Customer Section, we need proper form data.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#36]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
If we want to mass update the customer profile, here in the API we are facing some issues because of the form data. It is not taking the values.

**Steps to Reproduce**
**1.** Go to Postman -> Bagisto -> Admin -> Customers -> General -> Mass Update
**2.** We are unable to mass update as string issue is appearing.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-12-09 16-47-21](https://user-images.githubusercontent.com/92721837/206694391-838107d9-5d9f-47ee-a4d5-e86c9ecc5c4d.png)

**Expected Result**

We should be able to update the customer details.

**Comment by Aqib-Webkul** [comment]
This is not a issue value should passed like this 1,2,3

**Comment by Amitk-webkul** [comment]
This is working fine. [Here](https://tinyurl.com/2f9h5ef7)
