### ISSUE TITLE
On the Shop API -> Wishlists API - Get Customer Wishlist -> product details are showing null of the wishlist products.

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#360]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the Shop API -> Wishlists API - Get Customer Wishlist -> product details are showing null of the wishlist products.

**Please take the reference from the video below -**

https://webkul.chatwhizz.com/share/view-recording/66c4719589f0970bda195dcc

**Comment by amit-webkul** [comment]
Bug Fixed in this [commit](https://github.com/bagisto/rest-api/pull/330/commits/6a91cc932a692783e189e2501bb4d7be6cfda800)

**Comment by mukulsharma-webkul** [comment]
fixed, Get Customer Wishlist API is working fine.

**Video -**

https://webkul.chatwhizz.com/share/view-recording/66d556658e63b50c7252f06b
