### ISSUE TITLE
On the Shop API -> Theme API -> Please update the name of the API -> Get Theme Customization by id

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#362]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the Shop API -> Theme API -> Please update the name of the API -> Get Theme Customization by id.

**Please take the reference from the screenshot below -**

![themebyid](https://github.com/user-attachments/assets/809b48cb-dde3-409e-8636-958e45511b35)

**Comment by amit-webkul** [comment]
Enhancement Done in this [commit](https://github.com/bagisto/rest-api/pull/330/commits/6f9d611cfd7108ca5865123bbc0b613e3cb88974)

**Comment by mukulsharma-webkul** [comment]
fixed.

![id](https://github.com/user-attachments/assets/fad89cf7-608d-4898-9bd0-2b0587eed73b)
