### ISSUE TITLE
On the Shop API -> Products API -> unable to get the product data

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#363]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the Shop API -> Products API -> unable to get the product data.

1) Get Product list for the Shop API -> Unable to get the product list.
2) Get Shop product by id API -> unable to get the product.

**Please take the reference from the screenshot/video below -**

https://webkul.chatwhizz.com/share/view-recording/66c49dbfe5f9510e2d1deb98

**Comment by amit-webkul** [comment]
Bug fixed in this [commit](https://github.com/bagisto/rest-api/pull/330/commits/6a91cc932a692783e189e2501bb4d7be6cfda800)

**Comment by mukulsharma-webkul** [comment]
fixed, Get Product list for the Shop API and Get Shop product by id API is woking fine.

**Video -**

https://webkul.chatwhizz.com/share/view-recording/66d55ae560b8692d4c3a44bc
