### ISSUE TITLE
On the admin API -> Update Product (Simple, Virtual) -> getting exception in console

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#365]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the admin API -> Update Product (Simple, Virtual) -> getting exception in console.

**Please take the reference from the video below -**

https://webkul.chatwhizz.com/share/view-recording/66c5de5ee5f9510e2d20b449

**Comment by amit-webkul** [comment]
I have checked and found the API is working fine, I have recorded a video for your reference [link](https://webkul.chatwhizz.com/share/view-recording/66d15e4760b8692d4c363bbf)

**Note:** Make sure the channel, video, cross-cell, upsell, and related products entry are correct.

**Comment by mukulsharma-webkul** [comment]
working fine, by entering the data in correct way, API is working fine.

**Video -**

https://webkul.chatwhizz.com/share/view-recording/66d57161f7a4cb09e8b3cc90
