### ISSUE TITLE
On the Shop API -> Cart -> Update Cart Item API -> Giving invalid cart id but the response is not showing accordingly.[not found]

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#368]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the Shop API -> Cart -> Update Cart Item API -> Giving invalid cart ID but the response is not showing accordingly.[not found]

**Please take the reference from the screenshot/video below -**

https://webkul.chatwhizz.com/share/view-recording/66c6f34c89f0970bda1e6e43

**Comment by amit-webkul** [comment]
Bug Fixed in this [commit](https://github.com/bagisto/rest-api/pull/330/commits/71f9048ec3e14f772c9dce5f8fa6e3b8ab93736c)

**Comment by mukulsharma-webkul** [comment]
fixed, Update Cart API working fine now, if giving the wrong cart id then showing the relevant message.

**Video -**

https://webkul.chatwhizz.com/share/view-recording/66d55e158e63b50c72531a04
