### ISSUE TITLE
On the Shop API -> Cart API -> Delete all items from cart API -> Please update the response message.

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#369]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the Shop API -> Cart API -> Delete all items from cart API -> Please update the response message.

**Please take the reference from the screenshot below -**

![remove](https://github.com/user-attachments/assets/cd4d4857-012d-415d-bc45-daf34d2e8fdc)

**Comment by amit-webkul** [comment]
Bug Fixed in this commit [commit](https://github.com/bagisto/rest-api/pull/330/commits/f522261bba750838f66c5442df095b1241432757)

**Comment by mukulsharma-webkul** [comment]
fixed, Delete all items from Cart API is working fine now,

**Screenshot -**

![Screenshot from 2024-09-02 12-14-44](https://github.com/user-attachments/assets/a775ca05-c1ba-4e41-b5b3-5ed9b5e761fe)
