### ISSUE TITLE
In Mass Delete - Customer API, we are unable to delete the Customers.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#37]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we try to delete the Customers  in mass delete API, we are unable to delete it. We need to have proper form data for the same.

**Steps to Reproduce**
**1.** Go to Postman -> Bagisto -> Admin -> Customers -> General -> Mass Delete.
**2.** Here when we pass the data we are facing the issue.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-12-09 17-12-23](https://user-images.githubusercontent.com/92721837/206697073-bb419ce2-ac35-4042-a3d7-7954abc84bb8.png)

**Expected Result**
We should be able to mass delete the Customer.

**Comment by Aqib-Webkul** [comment]
This is not a issue value should passed like this 1,2,3

**Comment by Amitk-webkul** [comment]
This is working fine. [Here](https://tinyurl.com/2f6vnuer)
