### ISSUE TITLE
On the Shop API -> Cart API -> move cart item to customer wishlist API -> on giving wrong cart item id the response message not showing correct

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#370]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the Shop API -> Cart API -> move cart item to customer wishlist API -> on giving wrong cart item id the response message not showing correct.

Note - If the cart item id not exist then message should be showing not found.

**Please take the reference from the video below -**

https://webkul.chatwhizz.com/share/view-recording/66c71f60e5f9510e2d2360ae

**Comment by amit-webkul** [comment]
Fixed Issue In this [commit](https://github.com/bagisto/rest-api/pull/330/commits/f8518d6056ff1fcb4880c3c16c6f5672980d2cf4)

**Comment by mukulsharma-webkul** [comment]
fixed, now if cart item id not found showing correct message.

**Screenshot -**

![Screenshot from 2024-09-02 12-24-56](https://github.com/user-attachments/assets/4b3e3772-6f5a-40d5-8317-912d8c5f5a89)
