### ISSUE TITLE
On the Shop API -> Cart API -> move cart item to customer wishlist API -> please update the message

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#371]
Rest API - v2.2.0

Bagisto Core - v2.2.0

Description -

On the Shop API -> Cart API -> move cart item to customer wishlist API -> please update the message.

**Please take the reference from the screenshot below -**

![remove2](https://github.com/user-attachments/assets/4ea51ead-c09a-423a-8bc1-a00eca0bcd5c)

**Comment by amit-webkul** [comment]
Bug Fixed in this [commit](https://github.com/bagisto/rest-api/pull/330/commits/c2c36a9f5af54389e628538fb6753f6281dce985)
