### ISSUE TITLE
Duplicate routes in Bagisto and Rest API

### ISSUE THREAD

**Issue by JelleGroenendal** [bagisto/rest-api#372]
We noticed a duplicate route naming with a clean install of Bagisto and Bagisto Rest API

packages/Webkul/Admin/src/Routes/reporting-routes.php
Line 19: admin.reporting.customers.stats
Line 34: admin.reporting.products.stats

vendor/bagisto/rest-api/src/Routes/V1/Admin/reporting-routes.php
Line 26: admin.reporting.customers.stats
Line 33: admin.reporting.products.stats

When we run php artisan optimize it results in:

In AbstractRouteCollection.php line 247:
                                                                                                                                                          
  Unable to prepare route [reporting/customers/stats] for serialization. Another route has already been assigned name [admin.reporting.customers.stats].  
                                                                                                                                                          

Failed to run artisan optimize: exit status 1

**Comment by AliYazdanifar** [comment]
I have the same error

**Comment by Dansday** [comment]
@devansh-webkul I have same error

**Comment by KharisG1234T** [comment]
how to fix it?

**Comment by devansh-webkul** [comment]
We will fix it as soon as possible.

**Comment by devansh-webkul** [comment]
Fixed and provided v2.1.1 and v2.2.1.

**Comment by KharisG1234T** [comment]
> Fixed and provided v2.1.1 and v2.2.1.

ok thx,it's work

**Comment by KharisG1234T** [comment]
![image](https://github.com/user-attachments/assets/57edd957-ce65-44f6-8980-ad5bd4a4321c)
but in configuration i got this error

**Comment by amit-webkul** [comment]
Hello @KharisG1234T ,

This issue is not coming from the REST API.

The error clearly states that the 'info' key is undefined in your configuration section. This means that in your `packages -> Admin -> src -> Config -> system.php` file, one of the arrays is missing the 'info' key, which is required.

Please check this, and you should be able to find the solution.

Thanks.
