### ISSUE TITLE
We are unable to See the products in the Admin end also in the DB product flat table.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#38]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we create a product with API and Update the Same product with API, we are unable to see the product in Admin end and also, when we check the Database product table, there we can see the entry of the product.
Same entry can be seen in the product attribute values table, but when we check the product flat table we are unable to see the entry.

**Steps to Reproduce**
**1.** Go to Admin -> Check the product
**2.** Now Create a product and Update the product with API and check the DB.
**3.** There in the product flat table we are unable to see the product and also in the Admin end.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/207592026-1aa26fef-a9de-47df-a663-6b6cb329ac1a.mp4

**Expected Result**
Please fix the issue. Product should be visible at the admin end and also in the Database Entries so that we can check the API working properly or not.

**Comment by Amitk-webkul** [comment]
The issue is fixed.[Here](https://prnt.sc/JxkhfMr6Xicn)
