### ISSUE TITLE
Need to Add Readme File.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#4]
**Description**

When we check the details, there we can see that the **readme** file is **missing**. **Please** add the **readme** file for **API Module**.

**Screenshot**

Please check the screenshot for a better understanding of the concern.

![Readme](https://user-images.githubusercontent.com/92721837/204510466-1e26377d-e6bf-4faf-8ed8-d5a1d1045625.png)

**Comment by amit-webkul** [comment]
@Amitk-webkul , READ ME file added #86

**Comment by Amitk-webkul** [comment]
Added.

**Comment by Komal-sharma-2712** [comment]
Read me file added, so I am closing this issue:

![Screenshot from 2024-01-08 18-20-55](https://github.com/bagisto/rest-api/assets/63539748/7382f8cd-1d48-4696-818a-26d0efb6e628)
