### ISSUE TITLE
The status value should be shown in response while getting shipping details with all and id by Admin.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/rest-api#57]
**Terms**

 Before you open this issue, I have checked if the issue has already been reported.

**Bagisto Version(s) affected**

master

**Issue Description**

The status value should be shown in response while getting shipping details with all and id by Admin.

**Preconditions**

1. Admin should have at least one placed order.
2. Admin should have at least one shipment.

**Steps to reproduce**

1. Open getting shipping with all and shipment id inside Admin
2. Send a request
3. See the error

**Expected Result**

Here should be shown status value based on order status.

**Actual Result**

but It is showing null. [Here](https://tinyurl.com/2pl8x2m4)

**Screenshots**

No response

**Additional context**

No response

**Comment by amit-webkul** [comment]
Here, Shipments don't have any status. When we see the shipments at front end it is order status. [Look at the screenshot](https://prnt.sc/Ph0ZPWRIy_Fa)

**Comment by Amitk-webkul** [comment]
@amit-webkul While getting the shipping details here it should be shown order status in the response.

**Comment by amit-webkul** [comment]
@Amitk-webkul missing field added. Commit [Link ](https://github.com/bagisto/rest-api/pull/52/commits/6febdcb7175a19a82faa47c23bbd86c7212c3daa)

**Comment by Amitk-webkul** [comment]
The completed order status value is showing [null](https://tinyurl.com/2hk5xsue). [fron-end](https://prnt.sc/iFUOEVmyR6sy)
