### ISSUE TITLE
The update inventory API is not working properly. it is showing an HTML page.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/rest-api#58]
**Terms**

 Before you open this issue, I have checked if the issue has already been reported.

**Bagisto Version(s) affected**

master

**Issue Description**

The update inventory API is not working properly. it is showing an HTML page.

**Preconditions**

1. Admin should have at least one created product.

**Steps to reproduce**

1. Open update inventory API inside Admin
2. Send a request
3. See the error

**Expected Result**

Here should be shown product response
**Actual Result**

but It is showing an HTML page. [Here](https://tinyurl.com/2qetfqy3)

**Screenshots**

No response

**Additional context**

No response

**Comment by amit-webkul** [comment]
Here, Need to update endpoint URL to 

> `{{base_url}}/api/v1/admin/catalog/products/{{product_id}}/inventories`

![Screenshot from 2023-05-15 19-26-53](https://github.com/bagisto/rest-api/assets/121479029/99a459be-d7d9-4a14-bfce-1e37b0f65cc8)
