### ISSUE TITLE
In Customer Login API, Device Name should not be mandatory form data.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#6]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we check the Collection form data to login a customer, there we can see that the Device Name field is mandatory to fill, else we are unable to login the customer.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customer -> Authentication -> Customer Login.
**2.** Check the Form Data and there we can see the Device Name.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

![Screenshot from 2022-11-29 16-42-55](https://user-images.githubusercontent.com/92721837/204518460-3e98c1df-d44e-42fe-9f0a-2fa5aaf8a337.png)

**Expected Result**

The Device Name field should not be mandatory.

**Comment by devansh-webkul** [comment]
This is invalid for the stateless device name is mandatory.

**Comment by vivek-webkul** [comment]
Closing this issue as Invalid.
