### ISSUE TITLE
In the category no of products data should be shown in product response format.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/rest-api#61]
**Terms**

 Before you open this issue, I have checked if the issue has already been reported.

**Bagisto Version(s) affected**

master

**Issue Description**

In the category no of products data should be shown in product response format.

**Preconditions**

1. Admin should have at least two created category.

**Steps to reproduce**

1. Open get all category API inside product Admin/catalog
2. Send a request
3. See the error

**Expected Result**

Here should be shown no of products data in a proper response.

**Actual Result**

but It is showing in array form. [Here](https://tinyurl.com/2puq3twy)

**Screenshots**

No response

**Additional context**

No response

**Comment by amit-webkul** [comment]
This issue is already fixed in the [issue](https://github.com/bagisto/rest-api/pull/52)
