### ISSUE TITLE
The Attribute Mass delete API is not working.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/rest-api#63]
**Terms**

 Before you open this issue, I have checked if the issue has already been reported.

**Bagisto Version(s) affected**

master

**Issue Description**

The attribute Mass delete API is not working.

**Preconditions**

1. Admin should have at least one created attribute.

**Steps to reproduce**

1. Open mass delete Attribute API inside Admin/catalog/attribute
2. Send a request
3. See the error

**Expected Result**

Here should be deleted selected items

**Actual Result**

but It is not deleting it is showing an exception. [Here](https://tinyurl.com/2mj8xktg)

**Screenshots**

No response

**Additional context**

No response

**Comment by amit-webkul** [comment]
Here, 
The URL of endpoint is wrong.
Please do the change your endpoint URL as same like : **{{base_url}}/api/v1/admin/catalog/attributes/mass-destroy**

**Comment by Amitk-webkul** [comment]
Now working fine. [Here](https://tinyurl.com/2o8lark4)
