### ISSUE TITLE
Admin Meta Data API is showing an exception.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/rest-api#64]
**Terms**

 Before you open this issue, I have checked if the issue has already been reported.

**Bagisto Version(s) affected**

master

**Issue Description**

While getting meta data details it is showing an exception.

**Preconditions**

1. Admin should have meta data.

**Steps to reproduce**

1. Open get meta data API inside Admin/velocity
2. Send a request
3. See the error

**Expected Result**

Here should be shown proper data

**Actual Result**

but It is showing an exception. [Here](https://tinyurl.com/2kxtygpn)

**Screenshots**

No response

**Additional context**

No response

**Comment by amit-webkul** [comment]
Here, The end point URL is wrong. 
Please do correction in your collection.

> **URL :-**  {{base_url}}/api/v1/admin/velocity/meta-data

![Screenshot from 2023-05-15 18-07-03](https://github.com/bagisto/rest-api/assets/121479029/93eb8015-07da-4a6e-9bcb-01658775a8ea)

**Comment by Amitk-webkul** [comment]
Now It is working fine.[Here](https://tinyurl.com/2pxcxk7z)
