### ISSUE TITLE
While Updating the meta data API it is showing an exception.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/rest-api#65]
**Terms**

 Before you open this issue, I have checked if the issue has already been reported.

**Bagisto Version(s) affected**

master

**Issue Description**

While Updating the metadata API it is showing an exception.

**Preconditions**

1. Admin should have metadata.

**Steps to reproduce**

1. Open update metadata API inside Admin/velocity
2. Send a request
3. See the error

**Expected Result**

Here should be shown updating metadata.

**Actual Result**

but It is showing an exception. [Here](https://tinyurl.com/2qfjpga3)

**Screenshots**

No response

**Additional context**

No response

**Comment by amit-webkul** [comment]
Here, The end point is wrong. It should be **{{base_url}}/api/v1/admin/velocity/meta-data/{id}** .

![Screenshot from 2023-05-15 12-34-11](https://github.com/bagisto/rest-api/assets/121479029/d25de73d-0a08-4473-b78a-9a01daa2fae2)

**Comment by Amitk-webkul** [comment]
Now working fine. [Here](https://tinyurl.com/2zw3p49n)
