### ISSUE TITLE
The cart rule coupons mass delete and single delete are not working showing an exception.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/rest-api#69]
**Terms**

 Before you open this issue, I have checked if the issue has already been reported.

**Bagisto Version(s) affected**

master

**Issue Description**

The cart rule coupons mass delete and single delete are not working showing an exception.

**Preconditions**

1. Admin should have at least one cart rule.

**Steps to reproduce**

1. Open delete/mass delete cart rule API inside Admin/marketing
2. Send a request
3. See the error

**Expected Result**

Here should be shown proper response.

**Actual Result**

but It is showing an exception. [Here](https://tinyurl.com/2jbl6hnh)

**Screenshots**

No response

**Additional context**

No response

**Comment by amit-webkul** [comment]
The API is working fine on single delete cart rule coupons and the mass delete endpoint is wrong i have added valid endpoint in collection. Also i added here a reference video for better understanding.
 

https://github.com/bagisto/rest-api/assets/121479029/f048c6a5-11c9-4519-9a97-e929d5b89554

**Comment by Amitk-webkul** [comment]
It is working fine. [Here](https://tinyurl.com/2n527qwj)
