### ISSUE TITLE
The CMS mass delete API is not working showing resource not found.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/rest-api#70]
**Terms**

 Before you open this issue, I have checked if the issue has already been reported.

**Bagisto Version(s) affected**

master

**Issue Description**

The CMS mass delete API is not working showing resource not found.

**Preconditions**

1. Admin should have at least one CMS page.

**Steps to reproduce**

1. Open mass delete cms page API inside Admin/CMS
2. Send a request
3. See the error

**Expected Result**

Here should fetch the data and show successful full message data.

**Actual Result**

but It is showing a resource not found message. [Here](https://tinyurl.com/2qlj6e9j)

**Screenshots**

No response

**Additional context**

No response

**Comment by amit-webkul** [comment]
Here,
You need to pass correct id's in mass delete indexes. I have checked and found it is working fine. 
If you pass the wrong ID which is not available in DB so it will giving error **Selected resource not found**.

![Screenshot from 2023-05-16 15-27-25](https://github.com/bagisto/rest-api/assets/121479029/f08a4894-1b33-48d6-8a67-a7f0c27b5352)

**Comment by Amitk-webkul** [comment]
This is working fine.[Here](https://tinyurl.com/2nolzy6l)
