### ISSUE TITLE
Wishlist Product Add to Cart API ->  Message need to update.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#9]
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we add the **wishlist product** to the **cart**, there we can see the **message** appearing  "Item removed from wishlist successfully."

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customer -> Wishlist -> Add to Cart -> Send the product ID to move product to cart.
**2.** Now check the message, there we can see **"message": "Item removed from wishlist successfully."**

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

![Screenshot from 2022-11-30 12-05-08](https://user-images.githubusercontent.com/92721837/204724780-e2680985-20ac-4d01-9ea8-fc37ca52a902.png)

**Expected Result**

Here the message need to be updated.
Message should be - **Product Added to the Cart Successfully.**

**Comment by Amitk-webkul** [comment]
The issue is still there.[Here](https://tinyurl.com/2jpwzu2k)

**Comment by amit-webkul** [comment]
Please check the attached video, I have check and found it is working fine.

https://github.com/bagisto/rest-api/assets/121479029/f823cc67-1c26-4e56-a7f5-3161426bc62b

**Comment by Amitk-webkul** [comment]
@amit-webkul I have verified again and the issue is still there. [Here](https://tinyurl.com/2gxbtae2)

**Comment by Amitk-webkul** [comment]
Now this is working fine. [Here](https://tinyurl.com/2phpxvmq)
