### ISSUE TITLE
Can not login as Admin Rest Api

### ISSUE THREAD

**Issue by trannluongg** [bagisto/rest-api#95]
I am trying to login Admin Rest Api but am giving error: Call to undefined method Webkul\User\Models\Admin::tokens().
Please help me.
![Screenshot 2023-06-18 at 15 21 40](https://github.com/bagisto/rest-api/assets/46881031/c40f758e-104f-4029-a06a-670054510f17)

**Comment by Komal-sharma-2712** [comment]
I have checked admin login works fine with authentication token available. So I am closing this issue.
